### ISSUE TITLE
Migrating to Electron Forge

### ISSUE THREAD

**Issue by Aigeruth** [Zettlr/Zettlr#1055]
**This is a WORK IN PROGRESS issue to outline migration to Electron Forge based #938.**

# Goal

Zettlr uses [Electron Forge](https://www.electronforge.io/).

[Electron Forge](https://www.electronforge.io/) is one of the recommended build tool by [the official Electron website](https://www.electronjs.org/docs/tutorial/boilerplates-and-clis#electron-forge) and it uses webpack as bundler. It is more actively maintained than [electron-webpack](https://webpack.electron.build/) that could be used with [Electron Builder](https://www.electron.build/).

As we discussed on #938 and #1048, Zettlr should move towards Electron Forge.

## Using imports instead of global variables

Some of the packages are used in a way that assumes their presence in the global or window scope. This will not be compatible or easy to maintain with webpack, so as a preparation for this migration, they should be removed.

- [x] Import tippy.js explicitly #1056 
- [x] Import popper.js explicitly #1056 
- [ ] Import `$` for jQuery everywhere (or remove jQuery completely) #1062 
  - [ ] Prevent accidental use of jQuery #1071 
- [x] Import jquery-ui #1057 
    - [x] jquery-ui tabs
    - [x] jquery-ui sortable
    
## Moving the single package.json file
 
 Using two `package.json` files has not been required since [Electron 8](https://www.electron.build/tutorials/two-package-structure). Webpack would rely on a single `package.json`, so doing this upfront can reduce the size of that change.

- [x] Using `app.getVersion()` for version information #1090 
- [x] Utilising RequireJS for locating and importing libraries:
    - [x] CodeMirror (it is currently imported with relative path that explicitly contains `node_modules`) #1095
- [ ] Rest is done as part of https://github.com/Zettlr/Zettlr/pull/1060
 
## Improve code structure to work with webpack
- [ ] Replace `_autoload.js`

## Using a single index.html
 
Project has multiple HTML files currently:

- `source/renderer/assets/index.htm`
- `source/quicklook/index.htm`
- `source/print/index.htm`
- `source/log-viewer/index.htm`

These could be merged together a single HTML file with a different entry point for Javascript. It can be beneficial as there are overlapping parts between these HTML files. This will bring Zettlr closer to be a single page application that starts up based on routing, and can make easier to extend the usage of Vue.

This part is not mandatory as Electron Forge seem to support [multiple entry points](https://www.electronforge.io/config/plugins/webpack#configuration).

## Making theme management webpack compatible

- [x] Webpack's [lazyStyleTag](https://webpack.js.org/loaders/style-loader/#lazystyletag) feature can make the current theme structure work. See #1060 for details.

## Configuring Electron Forge

- [ ] Research migration path between Electron Builder and Electron Forge.
- [ ] Evaluate running Electron Builder and Electron Forge builds in parallel.

**Comment by tobiasdiez** [comment]
This looks really good. Thanks for the overview. If you could also extract the other points (in particular concerning the two package.json), then I'll have a look at the migration to electron-forge. Ok?

**Comment by nathanlesage** [comment]
Soooo, finally I arrived at this issue! :D

Overall, I am happy with the approach to finally get Zettlr to something more modern. However, some points, as I outlined in some other comments as well:

- First, we should simply remove everything that relies on jQuery and jQueryUI and instead implement this natively. Removes a lot of dependencies and will also look more native (which, in turn, should also be faster)
- Then, I would really like to have a chat on the proposed issues, because while this is a necessary and good step to do, we need to make sure the project ends up in a state that we can all work with. Therefore, I already dropped a comment somewhere that I'd like to have a chat with you over Jitsi sometime this or next week (--> hendrik@zettlr.com)
- Furthermore, concerning the single index.htm: Yes, please! I would really like to have the window controls globally available, as currently I have to do a lot of copy and paste whenever a new renderer window is entering the stage. Plus, we also need to finally replicate that VSCode menu style for Windows (and, ideally, optionally also for Linux), which will require some more code which will fit nicely this way. Concerning this, what I would like to propose would  be one centralized index.htm with a centralized app.js/window.js (whatever the name) that basically wraps the global functionality and pulls in the correct functionality for each window.
- Concerning LESS: Yes, I would really like to use a CSS compiler, as writing vanilla CSS is pretty tedious. However, the question of LESS-directives vs. CSS root-variables is not one of either-or. What we instead need (and this is something I'm advocating for since months now, but didn't have the time to do so) is to mitigate the LESS-compilation and also make most LESS-variables available as root-variables as well.

So, very very broadly speaking what I'm currently seeing is that we consolidate the currently rather messy toolchains to have …

- … components using VueJS (my plans are to rewrite the full renderer using vue as well, the sidebar was merely a case study, and it works pretty good right now)
- … the main process using TypeScript
- … and additional assets in their own toolchain (HTML and CSS, albeit I'd be willing to switch from Handlebars if anybody knows of a possibly better library for doing this)

So, finally, I am very much in favor of these initiatives, but I would like to coordinate the efforts during a call, so please make sure to send me a mail so that we can schedule a date!

**Comment by nathanlesage** [comment]
Whoops, sorry, didn't know the issue was linked!

**Comment by Aigeruth** [comment]
No worries. I did not expect that the ['Related to' expression](https://guides.github.com/features/issues/) will result in closure of the issue.

**Comment by nathanlesage** [comment]
Well, automation can be cool, but only if it doesn't do unexpected stuff 😄
