### ISSUE TITLE
[DEVELOP] Implementing a Defaults Writer | Importing/Exporting Options

### ISSUE THREAD

**Issue by nathanlesage** [Zettlr/Zettlr#1640]
Hey y'all,

yet another issue, because I've realized that refactoring the whole importing/exporting logic has a lot more potential than anticipated. I want to track the progress, and also discuss certain things, with this issue.

## What Is Going On?

We are currently refactoring the whole importing/exporting logic. The main difference to before is that, instead of using command line arguments for doing that (the fearsome Pandoc command that has caused a lot of issues recently) we are writing Pandoc defaults files for the same ends.

By implementing the first rudimentary forms, I realized some pretty cool stuff:

### Possible Improvements for the Importer

I realized we can set a lot of options for importing stuff, such as …

- always accepting or rejecting reviews in Word documents
- Wrapping (or not wrapping) text in the resulting Markdown file
- Making headings level 1 and 2 either ATX or Setext
- Make links references or inlines on purpose
- Put those references and footnotes after each block, section, or at the end of the document
- Extract any images or other media from container formats such as docx or ODT into a dedicated directory, making any links within the resulting document work out of the box

### Possible Improvements for the Exporter

Likewise, we get a lot of stuff for the exporters as well. Here, I've had the following ideas (please share your thoughts):

- The amount of options is incredible, so they possibly won't fit into the regular preferences dialog. This gave me the idea to extract them to a dedicated dialog. There we can do the following:
- Enable dedicated defaults files, suited for specific writers (e.g. HTML, Word, LibreOffice, etc.)
- Enable multiple files, that can be loaded on demand depending on what you want
- You can select one for each project
- You can quickly change them in the exporting popup

As you can see, a lot is possible. So please share your thoughts on what should make it into the 1.9! (Possibly 2.0 if I manage to implement a few other things on my bucket list)

## Roadmap

- [x] Implement a service provider managing all the available settings
- [x] Implement reasonable reference docs and templates for those exporting formats that support them
- [x] Implement a better formular handler (so that the amount of HTML to write is being reduced)
- [x] Implement a dedicated settings dialog for creating those defaults
- [ ] Implement @Kangie's defaultsWriter so that we have type checking in place
- [ ] Test it
- [ ] Release it ☑️

**Comment by Kangie** [comment]
Speaking of configuring pandoc, 

[Here](https://github.com/lackadaisical-documentation/lackadaisical-defaults-generator/blob/master/util/pandoc-schema.js)'s my attempt at putting together a JSONSchema for pandoc defaults files. Still todo is giving each item a meaningful description, but it may be useful in determining which options are useful where. 

I've also [ported](https://github.com/lackadaisical-documentation/lackadaisical-defaults-generator/blob/master/util/getWriter.js) pandoc's logic for picking a writer based on output filetype, if that's of interest. 

While we're at it I'm happy to put both the [markdown-binder](https://github.com/lackadaisical-documentation/lackadaisical-markdown-binder) and / or [markdown-processor](https://github.com/lackadaisical-documentation/lackadaisical-markdown-processor) modules up for consideration.

The markdown-binder will process an array of input files (i.e. the output of [this](https://github.com/Zettlr/Zettlr/blob/5a5b16ab28b8b3b2c5f11043d108397c9299320c/source/main/commands/dir-project-export.ts#L51), along with an optional configuration object, and return:

```JSON
{
  "properties": {
    "documentContent": {
      "description": "Concatenated Markdown content.",
      "type": "string",
    },
    "documentFrontmatter": {
      "description": "Object containing frontmatter keys.",
      "type": "object"
    },
    "pandocConfiguration": {
      "description": "The content of a pandoc defaults file, validated against a built-in schema",
      "type": "object"
    }
  }
}
```

The `markdown-processor` will concatenate MarkDown files appropriately for the OS, and ensure appropriate spacing, etc, to ensure that pandoc doesn't choke if the user has neglected EOF newlines (it's an extended dir-project-export command, basically). This output is documentContent above.

The `defaults-writer` takes two objects, parses the keys against the schema and outputs a valid pandoc defaults file. Optional 'writer' and 'output-file' parameters can be passed to the function to prevent the user from telling pandoc to output to an arbitrary format or location. Any keys that don't exist in the schema will be output as metadata keys.

Feel free to use any / all / none of the above. It's still early days, and I'm currently the only user, so if there's a function that could be reworked to fit in better here I'm happy to do so.

I'm not quite done porting it all across to typescript and writing appropriate tests. If anything doesn't work it will probably be fixed over the next few days.

**Comment by Kangie** [comment]
So here's my understanding of a pandoc defaults file, informed by the pandoc manual and jgm/pandoc#5990:

 - Command line options are root keys within the YAML file
 - Options that change / enable output within a template are Metadata: keys
  + These can be arbitrary values, so anything that doesn't configure pandoc should go under here.
  + I think, but have not yet confirmed, that this is how pandoc treats frontmatter keys.
 - Exceptions: 
  + `csl`, `bibliography`, `citation-abbreviation` (and possibly `toc` and `toc-depth`) root keys / command line options actually just set metadata keys behind the scenes (so that's what I'll do for defaults file output).

**Comment by nathanlesage** [comment]
Thanks for the research! @tarleb can you confirm?

**Comment by tarleb** [comment]
> Command line options are root keys within the YAML file

in general yes, with `input-files` and `filters` being special cases.

> Options that change / enable output within a template are Metadata: keys
>
> + These can be arbitrary values, so anything that doesn't configure pandoc should go under here.
> + I think, but have not yet confirmed, that this is how pandoc treats frontmatter keys.

It might be better to use `variables` instead. There's a subtle difference: metadata values are escaped, variables are included verbatim. E.g. `a_2` as metadata value gives `a\_2` in LaTeX, but is inserted unchanged when used as a variable value.

My gut feeling is that it's better to use the top-level options whenever possible; except if you use the variable in the custom template, in which case setting variables directly might be more robust.

**Comment by Kangie** [comment]
> > Command line options are root keys within the YAML file
> 
> in general yes, with `input-files` and `filters` being special cases.



> It might be better to use `variables` instead. There's a subtle difference: metadata values are escaped, variables are included verbatim. E.g. `a_2` as metadata value gives `a\_2` in LaTeX, but is inserted unchanged when used as a variable value.

Oops. I read that the wrong way, figuring it would be safer to put arbitrary values as metadata. Thankfully it's a simple change to put anything not in the schema under variables. I'll get on that!

> My gut feeling is that it's better to use the top-level options whenever possible; except if you use the variable in the custom template, in which case setting variables directly might be more robust. 

I'll do some testing and take a look at the pandoc repo. It would be good to work out which keys should be put under metadata, which under variables, and which behave best as root keys. I'm aiming for robust and generic, so we'll see which ones work best.

**Comment by the-solipsist** [comment]
> > It might be better to use `variables` instead. There's a subtle difference: metadata values are escaped, variables are included verbatim. E.g. `a_2` as metadata value gives `a\_2` in LaTeX, but is inserted unchanged when used as a variable value.
> 
> Oops. I read that the wrong way, figuring it would be safer to put arbitrary values as metadata. Thankfully it's a simple change to put anything not in the schema under variables. I'll get on that!

There are some subtleties that need to be kept in mind, though:
1. `reference-section-title` cannot be set as a variable (unlike `toc-title`), only as a metadata value.  This is because it is used by citeproc for processing, and not used as a template variable.
2. Similarly, with `suppress-bibliography`, `citation-style`, `csl`, and `bibliography`.  All of these need to be set either as root keys or as metadata keys (with `citation-style` being the exception, since that only works as a metadata key).
3. `table-of-contents: true` or `toc: true` should be set as a root key, not as a metadata key or a variable.  (If set as a variable, it won't work as expected across all formats.)

For more on the difference between metadata and variables, check out [this thread](https://groups.google.com/g/pandoc-discuss/c/tqMp0UKPpZQ/m/lay3hDAVBwAJ).

**Comment by tarleb** [comment]
You are right, excellent points! I had forgotten about that.

**Comment by nathanlesage** [comment]
> In Zettlr's case input-files won't matter as we're pre-processing the markdown input, but it'd be nice to handle this properly.

If we could be sure that Pandoc will treat them exactly in the order as we are passing them (@tarleb ?) then we could actually trash a lot of the export-project functionality and simply stuff the files into that variable. Because the parts of making image paths absolute and making sure footnotes work will be done by Pandoc itself, using the file-scope variable (don't pinpoint me on the exact name, but it's in the source already)

(e.g. all the concatenating stuff and preprocessing could be replaced by `defaultsFileContents['input-files] = projectFileList.map(fileDescriptor => fileDescriptor.path)`)

> There are some subtleties that need to be kept in mind, though:

Would someone mind to put together a list in the following form:

```
[property name]:
    - Root Level: [Describe the behaviour here, or "N/A" if it cannot be set at root level]
    - Metadata: [Yes, if it can be set using this, describe possible caveats, No if you can't set it meaningfully here]
    - Variables: [Same as Metadata]
[another property name]:
    - Root level:
    - Metadata:
    - Variables:

etc ...
```

I think this would help everyone: Zettlr, Matt, and everyday users of Pandoc.

Plus, I've spotted some unfunctional variables in the defaults template in the Pandoc defaults file manual section (and some undocumented, for instance there is this `trace`-property of which I am not sure what it does), so possibly, this could additionally be used for updating the docs of Pandoc itself?

Would anyone want to compile such a list? @Kangie? @the-solipsist? @tarleb?

**Comment by Kangie** [comment]
I'm happy to do it, but it may take a little while. 

It would be good to validate options and the defaults writer doing so, and would be a good addition to the repo for those trying to understand pandoc defaults files. The typescript port is "done", but I haven't yet stitched all of my modules back together, tested, and published them, and there's at least one new module that I need to write for my own purposes.

**Comment by nathanlesage** [comment]
> I'm happy to do it, but it may take a little while.

That would be great! There's no real deadline, because I'm one nanometer short of simply dropping the 1.9 plans and instead aim for 2.0, because I'm now homing in on the big construction sites that are necessary (complete CSS rewrite, migrate the renderer completely to Vue, switch to CodeMirror 6, and the new exporter)

**Comment by Kangie** [comment]
@nathanlesage 

[Defaults file writer](https://github.com/lackadaisical-documentation/lackadaisical-defaults-generator) is now written in Typescript, published on NPM, and builds + publishes using CI (based on your Citr workflows). 

I don't consider it 'done' by any means, but it seems to be generating valid defaults files, with a few caveats: 

* Keys are still all placed under 'metadata' if they don't match the schema. 
* I haven't actually validated the output in pandoc yet - Turns out tsc on Windows outputs JS with the wrong line endings and broke all of my docker stuff. Getting the CI sorted will let me test further, but the interface should be stable at this point.

The Readme on GitHub has been updated (but not on NPM until I publish a new version). You can now pass three (!) objects to the defaults writer and receive a single defaults file as output. My intended use is Document Frontmatter > Project Settings > Global Settings/Defaults by just being able to pass those objects to the function without **needing** to perform any logic in an app that integrates it... but you can process the objects yourself if you really *want* to. 

Still to come: 
* JSON Schema key descriptions
* Proper placement of keys in output (metadata vs variable)
* Complete list of (and handling logic for) special case keys (those that exist in the schema but shouldn't be output to the root.

**Comment by Kangie** [comment]
Ok, all seems to be working in my Docker container with the caveats above. I can't imagine that the interface will change from here and I'll get to work on documentation next week.

**Comment by Kangie** [comment]
So, I've had a little bit of time to test on production data and the defaults writer module appears to be working as intended. 🚀 

I will be changing the interface to the function to destructure the params (soon), but the logic shouldn't be seeing major changes from now on.

**Comment by nathanlesage** [comment]
> Caveats: I can't seem to trigger citeproc from a defaults file. Asked for help on pandoc-discuss, so I'll either fix that up or submit a bug. Seems more like a data issue, or an issue with pandoc than an issue with the function at this point. :)

Yeah, citeproc is a litle bit difficult, but here's how it goes:

- You can set the root-level property "citeproc" to "true" in the defaults file
- OR you can create a filter in the list of filters with "type: citeproc" (which allows different filters to run before and after citeproc), I've collected that with this docs: https://pandoc.org/MANUAL.html#default-files

**Comment by Kangie** [comment]
Turns out it was 100% an issue on my end; I somehow missed the `citeproc` key in my schema, meaning that it was always placed under `variables:`

But that's what testing is for, right?

**Comment by Kangie** [comment]
So, I've been doing some testing and have come to the conclusion that putting things under `variables:` rather than metadata may be a bad idea: 

* Apostrophes in the document `title:` cause build failures.
* Apostrophes in document `keywords:` cause build failures.
* Line breaks in the `title:` field do not appear to be preserved (further testing needed to put this down to `variables:` - it *was* working when the `title:` field occurred in the frontmatter block, but has stopped since I put it in a defaults file!)

Additionally `toc:` and `table-of-contents:` as root keys in a defaults file do not appear to actually enable generation of a TOC. 

I'm going to continue investigating these issues (next week, probably), but does anyone have insight into why this may be the case?

**Comment by nathanlesage** [comment]
No idea, BUT I just had an interesting conversation with Albert yesterday: Apparently we can use `tags` instead of `keywords` for tags with Pandoc. And where we can't, if I understood him correctly, Albert will open a PR addressing this, so at least one (miniscule) issue less.

**Comment by the-solipsist** [comment]
> Additionally `toc:` and `table-of-contents:` as root keys in a defaults file do not appear to actually enable generation of a TOC.

This is odd. I can't seem to reproduce this.  I use `toc: true` / `tables-of-cntents: true` in defaults files, and that works for me.

> Apostrophes in the document title: cause build failures.
> Apostrophes in document keywords: cause build failures.

That's odd.  Are you by any chance expressing the title and document keywords as single-quoted flow scalars?  If so, the apostrophes would need to be double-single quoted / escaped, or the entire title would need to be double-quoted.  Does https://www.yaml.info/learn/quote.html help?

> Line breaks in the title: field do not appear to be preserved (further testing needed to put this down to variables: - it was working when the title: field occurred in the frontmatter block, but has stopped since I put it in a defaults file!)

What kind of line breaks are you using?  

Do keep in mind that "metadata values specified [in defaults files] are parsed as literal string text, not markdown", whereas in YAML metadata blocks, "all string scalars will be interpreted as Markdown".

**Comment by Kangie** [comment]
Hi Pranesh, 

I haven't had a chance to properly validate my report above, so take it with a grain of salt (I got stuck writing a test case parser / test plan generator...). I really do appreciate your feedback here, and hope to have some time from Monday afternoon to actually perform some validation.

I'm using standard YAML syntax for title and keywords:

```yaml
title: This is a test title
keywords: 
 - Keyword
 - Keyword2
```
 I'd assumed (but obviously have not really checked) that passing a single apostrophe would be fine, e.g. `title: Matt's test title`. 

Looking forward to properly understanding the behaviour!

> What kind of line breaks are you using?

I'm using the following syntax for line breaks in the title: 

```yaml
title: |
  Product Name
  Operational Concept Document
```

When passed as a `variables:` key, the line break appears to be converted to whitespace, which is unexpected as using a pipe should preserve newlines and using `>` should replace them with whitespace.

I have **not** yet attempted to pass the title as a 'metadata:' key, so I don't know if this changes anything. 

Using this syntax (or very similar; I don't have my working example in front of me!) as in-document metadata does preserve the line break in the title and I have been using it to this point, but now that I'm setting the value in the defaults file I'll need to dig into it further.

> Do keep in mind that "metadata values specified [in defaults files] are parsed as literal string text, not markdown", whereas in YAML metadata blocks, "all string scalars will be interpreted as Markdown".

I'm pretty sure that I'm not using any sort of markdown markup in my testing so far, but I'll keep that in mind.

These are some initial observations that I haven't had any time to characterise apart from 'huh, that's unexpected'. It may turn out that some of these are from my poor understanding of YAML (possibly the apostrophe/single quote issue), which can be solved with some additional logic in the defaults writer.

I wouldn't expect an end user to know not to put an apostrophe in these keys, and honestly it was of my developers that raised the issue to me!

Pandoc is pretty mature, so I'm not expecting to find bugs in pandoc, just gaps in my understanding and implementation!

**Comment by the-solipsist** [comment]
Hey @Kangie. To be clear, I'm *certain* you're more of an expert of all these issues than am I! I'm just passing on things I've come across that I think might be helpful, in the hope that you do the figuring out. :smiley: 

On the title issue, while I haven't come across the problem you've described, could you still try the below?  I've had issues with newlines in titles working in PDFs otherwise.
```
title: |
       | D5.4
       | Some title
       | v3.0
title-meta: "Some title v3.0"
author-meta: "Anon Nymous"
```

Also, there are some metadata-only metadata options, like `title-meta` and `author-meta`.  You might consider including those in your generator for situations when you need to set the title or author in the exported PDF/DOCX/ODT's metadata differently from the main text.

**Comment by Kangie** [comment]
So, I get to eat my words.... the table of contents issue was actually a bug in my template!

toc; table-of-contents; and variables: { toc: true } all seem to work to generate a TOC now that I've removed a stray else switch!

I'm pretty sure that the module is ready for prime-time. I'm going to work on stablising the APIs over the next  week, working out the title and apostrophe issue that I'm having (possibly just move those keys to metadata...?) and then I'll work on integrating them into Zettlr. 

If anyone would like to test, the [lackadaisical-generator](https://github.com/lackadaisical-documentation/lackadaisical-generator) docker container can be checked out and built. It supports a bunch of cool things that I've had to implement lately, from building documents from yaml input  according to the schema (test cases) to a beamer template (which still has a buggy title page, because) and uses the defaults generator to configure multiple 'document types' with preset options. 

> - You'll need to use the command in the readme to call the docker container. That command works on the current directory by default and will parse the folder structure from that point.
> - You'll need to provide frontmatter that meets the schema. The minimums are:

```yaml
---
title: Lackadaisical Test
subject: test
keywords: 
  - test
---
```
and probably disable markdownlint rules `<!-- markdownlint-disable -->`, else the builds will fail unless your markdown matches my exacting standards... :P


@nathanlesage, with your permission, once the APIs are stablised I'll have a go at redoing the export function. My plan is to integrate the [markdown-binder](https://github.com/lackadaisical-documentation/lackadaisical-markdown-binder), which is an extended version of your current dir-project-export command forked a little while ago.

It does a few things: 
 - Transparently handles files with different encodings
 - Automagically strips BOM while concatenating
 - Makes image paths absolute (I just stole your code and typescripted it...)
 - Parses $ref: /path/to/file.ext to include content from another file without duplicating it*
 - Validates frontmatter against a schema (either built-in or passed to the function).
 - Accepts up to two objects to configure the defaults file  (say default + project settings), and parses the values from frontmatter.**
 - Returns an object containing: 
   - Markdown Content with Frontmatter stripped
   - An object containing Frontmatter
   - An object containing a pandoc defaults file

`*`I'm implementing this feature as we speak for the test-case stuff, so I figured why not extend that to markdown, and potentially frontmatter
`**` I only use frontmatter at the beginning of the first file parsed. Code needs to be written to parse a 'frontmatter' block anywhere in document content.

It accepts an array of files, so I'll probably just use the output of [this](https://github.com/Zettlr/Zettlr/blob/bbab68a636976e5b3884bb4f72c4e9446dadca29/source/main/commands/dir-project-export.ts#L54) and let Zettlr handle all of the various orderings. :)

If you think that's too much I'm happy to just implement the defaults-writer, but I'm maintaining and extending this code anyway...

Also, your pandoc wrapping helped me debug my own quick-and-dirty use of it the other day, thanks. :)

**Comment by nathanlesage** [comment]
@Kangie Sounds good :)

Just go forward with tampering with Zettlr's source! Those import/export modules need a rewrite either way so there's not much you could damage if you restrict yourself to those two modules (btw. a TypeScript rewrite of both would be much appreciated in case you feel generous :D)

Only one thing: I'm going to implement a dedicated settings dialog for every output format so that you can expect users to have a number of default files containing important info for the user to style and format their outputs corresponding to the output format – these would then be necessary to use with Pandoc. Don't know if that already works, just for your info :) The general idea is that Zettlr by default simply executes `pandoc --defaults-file "/path/to/file.yaml"` and nothing more (so that the inputs and outputs are also written to that file)

**Comment by Kangie** [comment]
I'm imagining (and wrote for) up to three settings objects being parsed to make the defaults file (in order of precedence):

1. Document Frontmatter
2. Project/Workspace Settings
3. Zettlr Settings.

If there's an additional 'document type' block, we should probably just merge it with the Zettlr base configuration object ourselves and send the result. Before I stablise that API next week I'm open to arguments about accepting more objects / an arbitrary number of objects.

**Comment by nathanlesage** [comment]
Hmm … we might want to think about that, but my time is incredibly limited until at least end of March :(

**Comment by nathanlesage** [comment]
Sooo, I have now begun working on a way to leverage defaults files for controlling Pandoc, and apparently [immediately uncovered a bug](https://twitter.com/zettlr/status/1371874381346041862).

I think the way I implemented it now gives much leverage for implementing the writers by @Kangie and @the-solipsist. In general, it's currently handled as such:

1. There are some [defaults files shipped with Zettlr](https://github.com/Zettlr/Zettlr/tree/develop/source/app/service-providers/assets/defaults), which are copied into the `./defaults` directory within the user data; one per writer (right now only a handful). This is being done in the new [AssetsProvider](https://github.com/Zettlr/Zettlr/blob/develop/source/app/service-providers/assets-provider.ts).
2. Whenever something wants to export, the [exporter's writeDefaultsFile](https://github.com/Zettlr/Zettlr/blob/develop/source/main/modules/export/write-defaults.ts) calls the appropriate function from the AssetsProvider to retrieve the defaults, with which we can then mingle. In the end, the whole file is being dumped to pass to Pandoc.

Therefore, if I remember the source code of the defaults exporter correctly, we simply need to call your defaults writer and pass both our own defaults object and the file to end up with the final one which we can write to disk, correct?

**Comment by Kangie** [comment]
Pretty much.

I had to temporarily my code a couple of weeks ago, but the issue has been resolved so I'll be publishing something again by the end of the week. 

If you give me until Monday I'll have a couple of options for you - I came up with a more elegant way to handle the file content processing that does all of the I/O up front.

**Comment by nathanlesage** [comment]
> If you give me until Monday

I'll give you as long as you want, there's so much broken in the app, that will take time :D Just cleaned yet another sewer today (which made TypeScript the major language in this repository 🎉)

> I came up with a more elegant way to handle the file content processing that does all of the I/O up front.

Looking forward to! As you can see, I'm currently attempting to model a GUI for editing these things, but I'll wait until I hear about your ideas.

**Comment by Kangie** [comment]
OK, basic WIP implementation is in #1818 - It should give you an idea of what I'm thinking here. I've also broken the regular export and print functions by focusing on dir-project-export, but that should be an easy fix tomorrow (today); it's all typing.

**Comment by nathanlesage** [comment]
Short update: Now there are defaults files for both import and export, and they can be edited from within the app. Now all we need is the defaults writer, which means that I'm gonna close this one in favor of #1818 🎉
