### ISSUE TITLE
[DEVELOP] Roadmap for Zettlr 2.0

### ISSUE THREAD

**Issue by nathanlesage** [Zettlr/Zettlr#1690]
Hello y'all,

another new roadmap issue! This time, I figured out the amount of changes I wanna pump into Zettlr both are legion and belong to a common theme. So here's a roadmap for Zettlr 2.0 (including all the other roadmaps). So, because I'm tired and stressed right now, here's the main takeaways:

- Unless there is something utterly urgent, I will **not** publish any new patches for the current Zettlr 1.x.x branch.
- I will take my time to prepare 2.0. Over the last three years I've made a lot of progress with regard to how you program an application, and while much has been migrated using new knowledge, there's still some way to go. And this time I want to get it right.
- This also means that the develop branch is for the time being **free for all**! Note that this doesn't mean you can just open PRs with weird features, but I'll be much more liberal because I really want to take the time to find bugs and fix them.

**Legend:**

👨🏻‍💻 = In Progress
😴 = Waiting to begin
✅ = Completely done

And now to what is going to change:

## Adapt the Application to Interface Guidelines corresponding to the different platforms 👨🏻‍💻

Many critics have lamented the lack of consistency across Electron applications, and I'm beginning to see why. After all, designing with already existing guidelines in mind is difficult, so many, including me, opt for a complete custom design which can then completely ignore any guidelines whatsoever. In order to silence those critics, but more importantly in order to give Zettlr's users a consistent look and feel, we need to adapt the application to the operating system interfaces that we find.

This, however, is pretty hard to do right, especially given the incredible amount of Linux window managers (Ubuntu, GNOME, XFCE, to only name the first three I remember), and the lack of unified design principles for Windows UIs (which Microsoft doesn't adhere to themselves many times). So we have to have a few compromises to make.

> See for the links to the corresponding guidelines the resources section below.

- Do not support every single Linux flavour there is. Instead, use the GNOME interface guidelines and apply system colours where appropriate (retrieve them using the [systemPreferences API](https://www.electronjs.org/docs/api/system-preferences#systempreferencesgetcolorcolor-windows-macos))
- Windows UWP guidelines recommend in-window settings. I'm not going to abandon the in-renderer modals just to reintroduce them for one platform. Instead, we'll fall back to an earlier version of the guidelines for this, where we can actually use a separate Window. An alternative would be to create a modal window on top of the main renderer and lock the window positions and sizes of both windows. Would be ugly, but an approximation. **To be discussed**
- By default, all styles will match the current platform in look and feel. However, this can be overridden partially with themes (see for a full explanation the section on the CSS rewrite).

## Engineering Challenges ✅

- [x] Devise a patching mechanism that can apply changes to the file tree without ever sending this whole thing down an IPC. This will enable to (a) show the main window immediately, filling the file tree iteratively, (b) make the app more snappy, (c) let me sleep at night because I know the algorithm works and doesn't suddenly break down
- [x] Move all find-functions in the file tree from hash-based system (sounded great when I began this four years ago, but is actually stupid) towards finding nodes (files/folders) based on their path. As some person has thankfully unearthed (too lazy to find the issue r/n), searching depth-first and breadth-first through the full file tree based on arbitrary numbers is completely inefficient. Rather, we need to search for paths, because the file tree is built using paths, so we can actually split a path we want into its constituent parts, and then follow the correct nodes immediately, without having to search possibly huge file trees where we could know beforehand that the file is not in there. This will even cut the algorithmic complexity of binary search, rendering this search `O(n)` where `n = Path segments`.
- [x] Bring back the native context menu. People have lamented this, and rightfully so. However, native context menus in Electron are hard, especially if you want to follow the security guidelines (displaying a fully compliant context menu requires you to gather context info in the renderer, send that to main, have main display the menu, and send back the result to the renderer). The custom application menu (necessary for Windows and Linux) can be styled with regard to the CSS rewrite below.

## Full Migration to VueJS ✅

> This supersedes #1641 

Zettlr 2.0 will – from a UI perspective – be based exclusively on Vue. This is to reduce boilerplate code, unify the application and finally follow one design system. Furthermore, the DOM code of the main renderer (and, to a lesser extent, all other BrowserWindows) is pretty chaotic. This will allow us to finally get the DOM right, and make it more concise.

## BrowserWindows and Dialogs 👨🏻‍💻

> See for this (especially the behaviour and styling of the windows) the corresponding interface guidelines below

### Block 1: Migrate the Dialogs to their own BrowserWindow Instances ✅

This only involves migrating the different dialogs to their own respective BrowserWindow instances, which are instantiated ~~using the `modal: true`-flag~~ (Using modals is discouraged, see [this](https://www.nngroup.com/articles/modal-nonmodal-dialog/)).

- [x] Migrate Preferences dialog (see the [Apple HIG](https://developer.apple.com/design/human-interface-guidelines/macos/app-architecture/preferences/), [Gnome HIG](https://developer.gnome.org/hig-book/3.4/windows-utility.html.en#preference-windows), [UWP Guidelines](https://docs.microsoft.com/en-us/windows/uwp/design/app-settings/guidelines-for-app-settings))
- [x] Migrate PDF-Preferences dialog (see guidelines for the preference window)
- [x] Migrate Pandoc error dialog
- [x] Migrate Paste-Image dialog (here we need a system-specific modal that blocks the window)
- [x] ~~Migrate project properties dialog (see guidelines for the preference window)~~
- [x] Migrate statistics dialog
- [x] Migrate development clipboard
- [x] Migrate about dialog
- [x] Migrate the tag cloud
- [x] Migrate tags manager
- [x] Migrate Custom CSS
- [x] Migrate the update dialog **Discussion: How should we do the update process in general?**

### Block 2: Adjust Behaviour of Windows 👨🏻‍💻

- [x] According to the Apple HIG, error messages should not be displayed as notifications, as we currently do, rather they should use alerts, which are implemented in the Dialog class of Electron ([see this page](https://developer.apple.com/design/human-interface-guidelines/macos/windows-and-views/alerts/)). **ToDo: How is this implemented on Windows and GNOME?**
- [x] Finetune window Chrome settings
    - [x] Windows 10 styling & functionality
    - [x] Linux styling & functionality
    - [x] macOS styling & functionality

## Migrate the PopUps ✅

In line with the goal stated below to abandon Handlebars, we have to migrate the Popups to VueJS. I'm just including this here so we don't forget it. The PopUps are actually pretty silly from a templating perspective, because we could've done these things without handlebars in the first place. However, the popups are about two years old, and back then I didn't really care about efficiency, because I wanted to learn.

However, how to migrate these will be interesting, because from a Vue perspective they don't really fit. We would need to mount a component as last in the pipeline and only show that when a popup should be shown, but then popups depend on local states, so I'm still unsure of how we should do this.

Maybe use Tippy for these things as well …? Ah, well, we have to go through the usage of tippy when following the design principles …

## ~~Complete~~ Overhaul of Translations ✅

So, something else I figured: Currently we use some HTML on Zettlr Translate to do some basic highlighting, but since we are switching to vue, and since using user-generated HTML might pose a security risk, ~~we need to re-do the whole translations~~ (Update Feb 13th, 2021: I figured we could instead just sanitize the translation strings, which I'm now doing instead ¯\\\_(ツ)\_/¯). ~~Gonna be fun, but most of this will be me fiddling with the database to remove all HTML tags, and instead use Markdown syntax for this.~~

I'll be pushing some changes in the future to mitigate that …

- [x] ~~Replace simple HTML markup tags with their Markdown equivalent (`<strong>`, `<em>`, `<kbd>`/`<code>`) and remove all other tags~~
- [x] ~~Strip all HTML tags from translated strings directly in Zettlr Translate~~
- [x] ~~Add a note describing the change in the translation service~~
- [x] Enable the `trans`-function to dynamically render Markdown to HTML in a safe way
- [x] Enable HTML output in the vue templates for translated strings

## Full Rewrite of the CSS 👨🏻‍💻

> This supersedes #1642

The VueJS migration relates heavily to a full rewrite of the CSS. While initially, three years ago, it seemed clever to divide the application styling into geometry and theme, it has proven that what themes do is only change colours, not geometry. So we can basically move everything into ONE single LESS codebase, and then just change colours with the themes. Furthermore, this will make the themes pretty small, only defining some variables, and nothing more. Additionally, we need a better handling of OS based styling, and we can simplify this much more.

### Block 1: Unify the base theme ✅

- [x] Move all geometrical definitions from the theme files to the Geometry base
- [x] Afterwards, rename geometry to Base theme (or something similar)
- [x] Also, make sure the editor styles are changed so that scrolling on both sides becomes possible (see https://github.com/Zettlr/zettlr-docs/issues/94)

### Block 2: Adapt the base theme platform-specific 👨🏻‍💻

- [x] Define everything themable with CSS vars, providing sensible defaults (`var(--some-colour, #ffffff)`) so that the app can run without any theme and still look good.
- [x] Define an Operating System theme, following the design principles of Windows, macOS, or Ubuntu, depending on the body class (remember the body receives a class based on the output of `process.platform`). This should form the defaults on a per-platform basis that were mentioned in the above task item.
- [x] Provide default Operating System styles so that Zettlr doesn't look like an Electron app
- [x] Choose platform-dependant styles for the custom menus.
- [x] Implement macOS Big Sur operating system styling
- [x] Implement Windows 10 operating system styling
- [ ] Implement Ubuntu operating system styling (note: We use the GNOME interface guidelines for overall UX, but as Ubuntu is the most consistently and, in my personal opinion, beautifully, styled variant, I want to replicate their styling for all Linux systems. This choice has to be made (a) to not drive me crazy with all the Window Managers that are around, and (b) because we can only check "Is this Linux? Yes/no" and cannot further subdivide)

### Block 3: Theming 😴

- [ ] Rewrite the themes so that they only set themable variables on the `:root` element. This will also make creating new themes more easy.
- [ ] Make sure themes don't interfere with the guidelines (so custom colours are totally cool, but especially with regard to repositioning items, we should be wary)
- [ ] Decide whether to leave it with a `dark`-class on the body, or manage the light/dark modes making use of `prefers-color-scheme` queries and apply that decision
- [ ] Enable the user to create custom themes via the GUI? (This will only be feasible if the amount of variables that are themable is not too big, so this item is pretty unsure)

> See for implementing operating system recommended styles the resources section on guidelines below.

## Full Accessibility Support 👨🏻‍💻

This is basically covered in issue #926. Refer to that one. **Here it would be great if some people would take it on them to fully test the accessibility support once Zettlr 2.0 goes into beta. Even better, some people with knowledge on Accessibility could integrate this iteratively as the basic rewrites are done.**

## Implement the new Pandoc Exporting/Importing ✅

> This supersedes #1481

This is also covered in another issue, see #1640. This also implies issue #1552, which has been closed. This point will be held back until we are sure how to control Pandoc reliably and have thought of a good system of doing so.

- [x] Modularise the exporter in such a way that we can easily add custom exporters, and, perspectively, export plugins. Possibly migrate to a provider?
- [x] Provide default exporters: "Default" (runs Pandoc to convert into the given format using the unmodified defaults files)
- [x] Provide default exporters: "PDF" (enables you to choose the method to export: Different LaTeX engines as well as "ChromiumPDF" (a.k.a. "printing" an HTML file to PDF))
- [x] Provide default exporters: "Textbundle" (enables exporting to Textbundle/Textpack, which does not require Pandoc at all)
- [x] Provide default exporters: "Reveal.JS" (since we need to apply some specific formatting after running Pandoc)

## Remove Handlebars ✅

While Handlebars is a cool project, it has always suffered from a host of problems:

- JavaScript-based templating is pretty much outrun by any framework such as Vue, React, or Angluar.
- Handlebars is pretty un-powerful and we have to add a lot of functionality ourselves.
- The syntax is actually not that nice and standards-compliant.
- Handlebars is not HMR-ready.
- Take a look at the file `./resources/dialog/preferences.handlebars` and decide for yourself if we shouldn't switch to a JSON schema for the preferences :D (Hint: Yes, we should)

This removal will be done by completely migrating to VueJS.

## Complete Migration to TypeScript 👨🏻‍💻

> This supersedes #1186

Also, this release will fully migrate the codebase to TypeScript. There is not much left, the main process is basically already written in TypeScript, only the renderers are still written in JavaScript, because I'm always afraid of breaking something. With migrating completely to Vue, this issue should eliminate itself along the way.

Points still to be discussed:

- [x] Do we want the Vue parts written in TypeScript? Or do we leave the script parts of the `.vue`-files in JavaScript? Right now I think the latter would make sense, but we should discuss this.

## Migrate the Editor to VueJS & Clean Up 👨🏻‍💻

Alright, the center piece is still a fragile beast. However, we can actually make this more efficient simply by moving it to Vue, because the main challenge here is state management. But with the right choices, this will be rather easy.

More specifically, we can make the documents a list of open files within the root component of the editor, and tie both the tab bar as well as the editor instance to it. Once the activeFile (or something like that) changes, those changes can be propagated to both the tab bar and the editor, ruling out any inconsistencies, and also making sure that only the necessary changes are applied to the dom. Added bonus: We can remove a lot of the boilerplate code currently residing in the zettlr-editor-class, which is only used for one single state management. This will reduce the codebase by a fair amount and will also finally enable us to implement long-wanted stuff such as disabling tabs altogether, hiding it based on variable states, et cetera.

But there are some additional changes that are necessary, for instance the fairly dumb context menus which could allow the renaming of an image by right-clicking, maybe even the resizing (resizing images is a matter of four lines of code if done right, so it's a possibility). Nevertheless, my main idea here is: Make the context menu adapt to whatever element is beneath the cursor.

- [x] Adapt the context menu to different contexts within the editor
- [x] Move the editor to its own vue component
- [x] Speed up initial loading, especially with many tabs open
- [x] Consistent switching
- [x] Enable user-based preferences for the editor (such as disabling tabbing)
- [x] If it's ready by then, migrate to CodeMirror 6 …?

## Cleanup 👨🏻‍💻

- [x] Fix all linter warnings and errors (see #1185)
- [x] Fix font loading (see #1447)
- [x] Look into the traffic light position issue (see #1374)
- [x] Peer dependency issue (see #1190)
- [x] Check that Tippy.JS is being used consistently. Right now it's being dropped in wherever I thought it would fit, without consistency. We have to check this.
- [x] Migrate all static assets to a central place in the app, rather than the current approach where the stuff is basically all around the ASAR file. (This means that every component that needs static assets will have those close by in an asset folder, and that asset folder needs to be copied to said central place. Why? Because this way the structure of `path.join(__dirname, 'asset/asset.ext')` will make sense both in un-compiled code and in compiled code, making it easier to trace any path issues.)
- [x] Ship every single language file to reduce the complexity of the app – every new version will then contain more languages if applicable, but downloading on the fly isn't necessary anymore). I don't want to re-instate this very fragile logic anymore.
- [x] Clean up the translation strings (e.g. shortly before release, someone needs to check if all strings are actually used)
- [ ] Clean up documentation
- [x] Enable a better titlebar/toolbar matching on macOS: While Windows and Linux will then simply feature both, on macOS a titlebar might be optional if there is a toolbar)
- [x] After we're ready, sanitise the filenames, `name`-properties, and positions of all new Vue components
- [x] Move all re-usable Vue components to their own dedicated directory under `./source/common`
- [x] Give the Markdown commands an overhaul; there is lots of room for improvement!
- [x] Move the whole search/replace functionality to the editor module and also improve the performance
- [x] Remove the `data.json` and move its contents to more appropriate places
- [x] Unify all code file extensions, all Markdown extensions, and all writer and reader (export/import) formats (at the time of writing, there are multiple places for where code file formats are defined, for instance)
- [x] Clean up the defaults files, and also add comments for user-transparency when customising them.
- [x] Add reference docs and templates for all writers where it makes sense
- [x] Enable to edit the iFrame whitelist in the settings (so that users can revoke whitelisted hostnames)
- [x] Remove the list of variables from the snippets editor and create a proper docs page for that.
- [ ] More …?

## Resources / Further Information

- [Apple Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/macos/overview/themes/)
- [GNOME Human Interface Guidelines](https://developer.gnome.org/hig/stable/)
- [Windows UWP Guidelines](https://docs.microsoft.com/en-us/windows/uwp/design/usability/)

Stay tuned!

**Comment by tobiasdiez** [comment]
Sounds amazing! Two quick pointers:
- If the css uses sass variables systematically, then one would get a very clean way to customize the colors in the themes (for example, similar to how bootstrap does it)
- Typescript support got an enormous boost in Vue3: https://v3.vuejs.org/guide/typescript-support.html#typing-reactive

**Comment by nathanlesage** [comment]
Thanks! Yeah, I wanted to actually dump internal variables as much as possible, in order for users to set those variables in their custom CSS. So, of course, I'll be setting systematical variables for the geometry stuff in the template to make it customizable per release, but the rest I want to do with variables, because that has been a request, and I also see the benefits of this approach!

But please feel free to check the new source code if you want to make sure it's consistent!

As for Vue: I hope that the necessary plugins get Vue3 support so we can go there as well :) Thanks for the hint!

**Comment by bionicles** [comment]
how would one get rolling on a 2.0 dev branch? i have linux and mac rigs and could possibly contribute. I don't know Vue but I do know JS, React and CSS pretty well. Big fan of immutability + functional programming. 

If you haven't checked out [Ramda](https://ramdajs.com/), I would like to reach through the internet and smack you. Could make your job way easier @nathanlesage (!)

**Comment by Kangie** [comment]
@bionicles Your best bet would be to submit PRs to develop at this point, based on my understanding of the push towards 2.0.

**Comment by nathanlesage** [comment]
@bionicles Right now, I'd appreciate it if you waited; I'm currently in the process of moving large chunks of code around so that the final structure works out. This might take a while and until then I prefer to do this alone so that I know what is going on. But as soon as that is finished, I welcome each and every PR that helps get Zettlr 2.0 rolling, because there are a lot of bugs and improvements to be done.

With regard to functional programming: Zettlr uses a mixture of both functional programming and OOP, and I intend to leave it with that. Both styles have their own benefits and drawbacks, and I feel pretty sure we're heading towards a good mixture of both approaches. Especially where centralised state management is concerned, I am pretty happy having classes and objects.

**Comment by AleksueiR** [comment]
Since you mentioned a full CSS rewrite, maybe you might consider using [TailwindCSS](https://tailwindcss.com) for styling the front-end.

**Comment by nathanlesage** [comment]
@AleksueiR Mh, I'm not sure this is what we can use here. For Zettlr 2.0, I want to actually build the macOS/Windows/Linux components, and I need a hefty amount of CSS to achieve that in the first place, so I think for Zettlr's case, adding Tailwind would actually increase complexity.

***

Anyways, short update:

The new main window code is now pushed to the codebase. I've ripped apart a lot of stuff, so expect things currently to be broken. Furthermore, you can, if you want to, begin adding Windows and Linux scoped styles to the most general elements (toolbar, window title, window controls, basically everything that's in the common/vue/window-folder) because these are from the DOM perspective most stable right now.

The general idea behind the CSS rules in the Vue components:

- Namespace everything to `body` and `body.dark`
- Separate by general rules (which are the same on all platforms) and then add three distinct set of rules, namespaced to `body.darwin`, `body.win32`, and `body.linux` respectively.
- However, all of the above is right now still not completely consistent, but that's at least the final idea I see for these.

**Comment by pcuci** [comment]
Maybe I missed it; are there plans to make Zettlr more modular, so others can more easily build plugins for it, and hopefully address the ambitions in #921?

Ideas from [Everything’s a Plugin: Understanding Webpack From the Inside Out](https://www.youtube.com/watch?v=xse6JKcfbzs) might help :-)

**Comment by nathanlesage** [comment]
Somewhat more modular, yes. Real plugin system? Not right now. And webpack won't help at all. We're using this just to compile the code, it's not shipped or used during runtime.

**Comment by pcuci** [comment]
> Real plugin system? Not right now.

Looking forward to that! :-)

I meant the plugin philosophy from WebPack; more of a Unix "pipe everything" approach than anything.

I actually tried using [Joplin](https://joplinapp.org/) as a backend for Zettlr (needed mobile access for note taking), and while their design has a SQLite database storing all the information (which makes sense for real-time cross-platform data syncing), their import and export functionality is not idempotent, so using Zettlr on the desktop—while more fun as an editing experience—ended up being a pain for persistence and data integrity... (losing notes sucks)

I don't see a cross-platform (mobile + desktop) milestone in the 2.0 roadmap (which might be the right thing for this community, don't know).

However, a plug-in friendly system architecture that would allow to swap or add additional persistence layers might come in handy, at least for my mobile-first use cases.

Other ideas to support collaborative on-the-go multi-user-at-same-time note-taking and knowledge making?

**Comment by nathanlesage** [comment]
> I don't see a cross-platform (mobile + desktop) milestone in the 2.0 roadmap (which might be the right thing for this community, don't know).

That is not at all a possibility. I hardly manage to work on Zettlr. I am hence unable to start yet another project, and will not do that. For this, someone else has to step up. I don't really get it why no one has started coding like a file-only WebDav-based mobile MD editor, but I guess right now most people are too busy trying to make 20 bucks from mobile sales, so possibly that's why. But Zettlr on mobile? That's a 100 % certainty won't come.

> However, a plug-in friendly system architecture that would allow to swap or add additional persistence layers might come in handy, at least for my mobile-first use cases.

Yeah, would be cool, but as I said: I won't start building a plugin architecture if the baseline system is *that* bug-ridden.

> Other ideas to support collaborative on-the-go multi-user-at-same-time note-taking and knowledge making?

Again: You have some cool ideas, but you're completely forgetting about the rigid time constraints here. These ideas are all cool, but the main reason why those obviously cool things aren't yet implemented is because these are – from a programming perspective – ridiculously hard problems that take either a CS M.Sc. degree or a ton of time to do.

**Comment by mattj23** [comment]
@nathanlesage, is the `develop` branch where you're currently doing your work on 2.0?

**Comment by nathanlesage** [comment]
@mattj23 Yes, it is

**Comment by tonysepia** [comment]
@nathanlesage I have a question about the _"Move all find-functions in the file tree from hash-based system (sounded great when I began this four years ago, but is actually stupid) towards finding nodes (files/folders) based on their path."_

I'm about to start a new Zettelkasten structure (moving from OneNote). Should I arrange my files in a particular way to be able to harness this upcoming move to the new find-function system? I.e., should I split notes into fodlers by topics/dates?

**Comment by nathanlesage** [comment]
No need to change anything on your side – what I've outlined is a purely engineering challenge that I face, it does not affect the structure of your notes in any way!

**Comment by tobiasdiez** [comment]
Quick feedback about the design on Windows:
- Using blue for highlights is confusing and inconsistent. I thought Zettlr's branding color is green. I would stick to this.
- The font in the file browser is too small and not very readable, especially for tags: 
![image](https://user-images.githubusercontent.com/5037600/118777434-5b7ed080-b889-11eb-9804-262a301d5754.png)
- Is it possible to hide the "words" information. I don't really care about this and it takes up quite some vertical space.
- The color difference between the top menu and the file tabs is too much in my opinion (maybe use the lighter gray from the file selection sidebar?)
- The "tabs" header (General, Editor, ...) in the preference is rather small, and could use some spaceing between the options
- Add a bit of horizontal space between checkbox/togglebox and the label. Moreover, the label should be horizontally centered with respect to the togglebox (right now they are on the same baseline, which looks strange as the togglebox is slightly bigger).

**Comment by nathanlesage** [comment]
> Using blue for highlights is confusing and inconsistent.

The blue is your Windows' general highlight colour – for me it's pink. It's part of making Zettlr look really native, and NOT using CSS in any way possible, but rather make the app look fully native.

But yes, right now the Windows build is in a "working" state, certainly we can improve that!

**Comment by tobiasdiez** [comment]
Mhhh, but isn't the branding / recognization aspect more important than a native look? Not even Microsoft's own applications (Word, VS etc) are using the general highlight color. I liked that in previous versions one color was used for highlights in the markdown as well as in the rest of the application. Gave a very nice and consistent look.

**Comment by nathanlesage** [comment]
Mhh you got a point there. (The main point for me was to test out how far I can get to actually native look, not necessarily a strategic decision that we'll be using these overall.)

What I'd like to get to is the following: Have all elements actually look like native inputs, but then choose via theme either "System" (using, e.g., the OSs branding) or one of the other available themes. What do you think?

**Comment by tobiasdiez** [comment]
Sounds like a good idea!

**Comment by nathanlesage** [comment]
Perfect. I'll remember this while refactoring the themes to `:root var()`-only CSS files in the next weeks!

**Comment by bionicles** [comment]
Hey @nathanlesage what are your blockers on the project? Perhaps we can all brainstorm about them (or, more likely, you'll figure problems out by telling us about them)

**Comment by nathanlesage** [comment]
@bionicles The biggest blockers are in fact through right now. What I am currently doing is specifically fixing smaller things, improving the code, making it cleaner and so on. There are still quite some TODOs, but the biggest thing that's currently stopping me from starting the public beta is that I still have no one who has had a **thorough** look at the Linux appearance of the app and the Windows appearance. I want at least one person confirming that the app looks decent so far and we can give it to users.

So what that would involve is basically to run the app on Windows 10 and one (or ideally a few more) Linux distribution, make sure that it looks decent, and confirming that with me. Optionally also altering the styling to make it look this way.

As long as I'm waiting for this to happen I'm continuing to fix all those minor things and aim at bringing the issue list to fewer than a hundred.

**Comment by bionicles** [comment]
Which version do you want us to run? Want screenshots or for us to follow a present test scheme for reproducibility?

**Comment by Kangie** [comment]
@nathanlesage 

A bit late, but #2065

If you can give me some pointers as far as getting the webpack to work when you have time, I'll see what I can do about getting some side-by-side Windows/Linux observations going.

**Comment by nathanlesage** [comment]
> Which version do you want us to run? Want screenshots or for us to follow a preset test scheme for reproducibility?

The most recent develop-version is the right one. And yes, screenshots would be great. In general, just compare how Zettlr looks and feels with regard to other standard apps that you feel are paradigmatic for that OS. The design is to a certain degree purely subjective, and I trust your gut feeling with that!

For instance, to see how it should look like on macOS, I simply open one of the Apple apps and look for UI elements I want to mimick. On Windows, it might be, e.g., the Windows Calendar, the calculator, whatever looks the most native.

So, if you think something looks off, it's best to have both apps open and describe it so that I have a reference to adapt the design with!

***

@Kangie 

Sorry for answering so late, I saw your PR and as far as I can see it looks alright. I'll be taking another look soon!

With regard to webpack: I have actually no idea how precisely that works, since it's only being utilised by electron-forge. But in general the build should "just work". If not, is there some specific error …?

**Comment by 8hur** [comment]
Given how many improvement the develop build seems to have received, do you expect to push alpha/nightly builds for people to take a peek, and maybe gather feedback on the overall modifications, any time soon? I know I'd be interested but i would understand if you'd rather have dev feedback until you can push a beta version of the 2.0 branch.

**Comment by nathanlesage** [comment]
@8hur In general, I'm always sympathetic, but I know that quite the avalanche will get to me once I begin releasing betas, so currently my aim is to fix everything that's fixable before going to beta, since the amount of open issues can at times induce stress, and I try to reduce that as much as possible. I hope you understand!

**Comment by lduktus** [comment]
@nathanlesage could you give a hint/startingpoint on where to look at for the Linux relevant todos (Adjust Window Behaviour and Adapt the base theme platform-specific). I would be really thankful for a short hint à la check these files as I have never worked on a bigger js/electron project. (If somebody is already working with this I can also help with debugging and testing.)

> Enable the user to create custom themes via the GUI? (This will only be feasible if the amount of variables that are themable is not too big, so this item is pretty unsure)

Just my uneducated thoughts, if I am sorry if I miss something obvious:
Imho the current themes have only marginal differences? Besides the font-family and the "main" color most UI elements look and feel the same. I think switching between different primary colors, a main font-family and maybe a small selection of styles for buttons, popups etc. would be nice. 
The theme selection could be somewhat like this:

Choose main-color: red blue green yellow custom
Choose style: material, solid, minimal (not necessarily good categories, but I think the idea is clear)
Choose main font: sans serif, serif, monospaced

And for more advanced customization there is still custom css.

**Comment by nathanlesage** [comment]
> could you give a hint/startingpoint on where to look at for the Linux relevant todos (Adjust Window Behaviour and Adapt the base theme platform-specific).

@lduktus It's understandable that it's not easy, but here's a general breakdown: I recommend you run the code directly (using `yarn test-gui`) and then open the DevTools. Then, use the "inspect element" functionality and hover over any element where you think that the styling could be improved (and click it).

Then you need two infos: First, the file where the corresponding styling is being defined (mostly will be .vue, but can also be a .less file). Then open that file and adapt the styling. All styles are namespaced to the `body` element and then in your case the `linux` class. It can be that some elements do not already have a `body.linux`-styling section, in which case you can create one. See the screenshot for details:

![image](https://user-images.githubusercontent.com/17251683/126863425-48ba01dd-6785-4674-a16c-f2381cb31b25.png)

And this one:

![image](https://user-images.githubusercontent.com/17251683/126863646-269677bc-4e25-4d10-b6cb-9ee9648df465.png)

**NOTE**: Some styles are not defined within Vue-Components, but in generic files. There are the following generic files:

* https://github.com/Zettlr/Zettlr/blob/develop/source/common/modules/markdown-editor/editor.less --> Contains styles for the main Markdown editor (the "big" one)
* https://github.com/Zettlr/Zettlr/blob/develop/source/common/modules/window-register/assets/geometry.less --> Contains a few geometry-styles that pertain to many components at once
* https://github.com/Zettlr/Zettlr/blob/develop/source/common/modules/window-register/assets/application-menu.less --> Contains styling for the menus, i.e. both the application menus and the context menu
* https://github.com/Zettlr/Zettlr/blob/develop/source/common/vue/window/assets/generic.less --> Contains generic styling for some elements, i.e. the dropdown lists and generic input elements

**Comment by almereyda** [comment]
Just a quick note on a certain point that was not elaborated a lot before here:

> Points still to be discussed:
>
> - [ ] Do we want the Vue parts written in TypeScript? Or do we leave the script parts of the .vue-files in JavaScript? Right now I think the latter would make sense, but we should discuss this.

From a consistency point of view, it seems legit to have all the code base in a single language, and also profit from the type system to ease out errors in the same time.

**Comment by nathanlesage** [comment]
@almereyda I haven't told anyone yet, but my plan is to reserve the full 2.1 iteration solely for completely migrating the codebase to TypeScript and Vue3. This won't happen in 2.0 but of course you're right!

**Comment by almereyda** [comment]
Thank you for the quick and specific update. I had only found this question
unanswered up until now, and am happy with the explicit plan to do this
kind of maintenance work on the codebase.

**Comment by nathanlesage** [comment]
Closing the roadmap since we've now addressed more or less everything! The few things which didn't make it into 2.0 will come in 2.1, but these are mostly code-styling issues, so nothing lost here :)
