### ISSUE TITLE
[Feature Request] Tray QuickNote

### ISSUE THREAD

**Issue by nathanlesage** [Zettlr/Zettlr#175]
When implementing a Zettelkasten, what you might want to do is have the option to quickly enter new thoughts into it. Therefore, we'll implement a Tray icon enabling a quick entry. This feature is targeted towards the `1.4` release, if possible.

## Proposed solution

1. In the preferences, enable the Tray QuickNote and set several options for easy access, such as:
    - The folder in which they are placed automatically
    - File name patterns (such as: `%id %firstline.md` for example)
2. When you have a thought or find something online, simply click on the Tray icon to bring up the quick entry window
3. Enter the thought using standard Markdown, highlighted using Zettlr's theme
4. Add links, tags and what else you need
5. Possibly overwrite the target folder and the filename
6. Click "Create" and have the note added to your Zettelkasten.

## ToDos

- [ ] Add a window class
- [ ] Add a service provider for the Tray Window
- [ ] Add a command to enter the final note
- [ ] Solve the Tray limitations on Linux systems. See the [Tray Class Documentation](https://electronjs.org/docs/api/tray)
- [ ] Testing

**Comment by nathanlesage** [comment]
Oh, I forgot that I need to ask for help from you:

WINDOWS USERS: How are such quick windows commonly done on Windows? Is this concept even applied on Windows so far? If so, how would you think it would fit best into your current Windows workflow so that the window doesn't distract you?

LINUX USERS: How are these things done on Linux? Please bear in mind that internally, the app can only see "Linux or not Linux" and cannot distinguish between different Linux distributions. I would like to find a common solution that works for all Linux distributions equally good.

Please share your thoughts here so that we can work out a solution that works best for all of us without reinventing the wheel :)

**Comment by yashha** [comment]
Remembers me to this: ;) 
https://www.thedigitalmarketingguy.net/articles/windows/disable-or-remove-send-to-onenote-in-windows.html

Why not just adding a try icon with fields like for now.
"Open Zettlr"
"New Quicknote" (Opens Zettlr with an Draft (no File name, not saved) or Opens quicknote window)
"Close Zettlr"

When clicking on the tray I would rather like to open the real Zettlr.

**Comment by nathanlesage** [comment]
Opening a draft is currently not possible, files have to be created prior to editing … so this would have to wait until the tabbed mode is implemented :(

**Comment by danieltomasz** [comment]
i would add also “search note” option

**Comment by Zverik** [comment]
Tray is a nice to have, although may be not for 1.7. Let's not lose this to the stalebot.

**Comment by nathanlesage** [comment]
> Let's not lose this to the stalebot.

Stalebot, collector of souls

**Comment by canpolat** [comment]
> WINDOWS USERS: How are such quick windows commonly done on Windows? Is this concept even applied on Windows so far? If so, how would you think it would fit best into your current Windows workflow so that the window doesn't distract you?

I don't know how technical a response you are looking for, but as far as I know, Microsoft OneNote impelements this. [Here is an old description about the functionality without the taskbar icon](https://support.microsoft.com/en-us/office/create-quick-notes-0f126c7d-1e62-483a-b027-9c31c78dad99). They have an icon in the notification area, something like this:

![image](https://user-images.githubusercontent.com/459891/87229984-eca13300-c3ac-11ea-99f4-a1c56c74131e.png)

**Comment by nathanlesage** [comment]
@canpolat Thanks!

**Comment by v3ss0n** [comment]
Lets start with just a simple tray icon. Click and it will show zettlr , currently that is only thing missing

**Comment by marcinsmialek** [comment]
Having a tray icon and configurable system-wide shortcut would be great, at least for Windows.

Such quick note should be created from a configurable template, where one could use macros, like current date and time.

**Comment by v3ss0n** [comment]
yeah tray is only thing preventing me from using this great tool.
i am now using joplin and looking forward to change.

**Comment by cskeogh** [comment]
Hi, I am part of a team of six students [UofA-SPI21-team7](https://github.com/UofA-SPI21-team7) from University of Adelaide Software Engineering program and we would like to work on this issue. Our plan is:
- 12 Apr 21 – provide our design and user interface mock-ups
- 3 May 21 – provide our initial code pull request
- 17 May 21 – provide our updated code pull request, addressing review comments
- 24 May 21 – provide documentation pull request

**Comment by nathanlesage** [comment]
@cskeogh Thank you for the detailed roadmap. Take your time, I am looking forward to receiving your PR.

As for the documentation pull request, just to make sure: The documentation repository is here: https://github.com/Zettlr/zettlr-docs. The English translation would be sufficient. If you have questions as to the structure of the documentation, just open an issue with your questions _beforehand_ over there, since we employ a customised MkDocs structure which might not be self-explanatory.

Thank you!

**Comment by cskeogh** [comment]
Hi, this is [UofA-SPI21-team7](https://github.com/UofA-SPI21-team7) proposed tray design. Comments welcome. The design is consistent with [comment 703186459](https://github.com/Zettlr/Zettlr/issues/175#issuecomment-703186459).

_Note:_ Our team's project has a fixed schedule. If our team has time, we can propose additional goals with advanced features such as new note, search, user configurable menus, etc.

1. Add `Leave app running in notification area when the window is closed` to **Preferences** ➔ **Advanced**.

   1. Defaults to true on Windows.
   1. Defaults to false on MacOS because the MacOS dock provides convenient quick access.
   1. Defaults to false on Linux because Gnome/KDE/etc provides convenient quick access.

   ![Design preference](https://raw.githubusercontent.com/UofA-SPI21-team7/zettlr-assignment/main/images/Zettlr%23175-design-preferences.png)

1. When `Leave app running in notification area when the window is closed` is false, Zettlr design is unchanged.

1. When `Leave app running in notification area when the window is closed` is true:

   1. Zettlr tray icon is visible in notification area when Zettlr is running. Tray icon is visible when Zettlr window is visible too. This is consistent with [Slack app](https://slack.com) and many more apps.

   1. Selecting **File** ➔ **Quit** will quit. This design is unchanged.

   1. Clicking 🗙 in top-right of Zettlr window title bar will hide Zettlr. Zettlr will not quit.

   1. Windows 10:

      1. Left click the tray icon will show and bring-to-the-front the Zettlr window in the last displayed location in the last displayed size.

         ![Design taskbar](https://raw.githubusercontent.com/UofA-SPI21-team7/zettlr-assignment/main/images/Zettlr%23175-design-taskbar.png)

      1. Right click the tray icon ➔ **Quit** will quit Zettlr. Same function as File ➔ Quit. Any changes will be autosaved. I don't think Zettlr has any blocking features (e.g. "Are you sure?" popups) that would block a quit action.

         ![Design Windows 10](https://raw.githubusercontent.com/UofA-SPI21-team7/zettlr-assignment/main/images/Zettlr%23175-design-taskbar-with-quit-Windows-10.png)

   1. MacOS:

      1. Left click the tray icon ➔ **Open Zettlr** will show and bring-to-the-front the Zettlr window in the last displayed location in the last displayed size. MacOS doesn't support left/right click the tray icon, function is slightly different to Windows 10.

      1. Left click the tray icon ➔ **Quit** will quit Zettlr. Same function as **File** ➔ **Quit** (changes autosaved).

         ![Design MacOS](https://raw.githubusercontent.com/UofA-SPI21-team7/zettlr-assignment/main/images/Zettlr%23175-design-taskbar-with-quit-MacOS.png)

   1. Linux - Gnome desktop:

      1. Requires system library libappindicator to be installed (not installed by default on Fedora 33 but available in Fedora default repositories).
      1. Requires gnome-shell extension [AppIndicator Support](https://extensions.gnome.org/extension/615/appindicator-support/) to be installed.
      1. Detect if the libappindicator and [AppIndicator Support](https://extensions.gnome.org/extension/615/appindicator-support/) are installed. If support not detected, disable (grey-out) `Leave app running in notification area when the window is closed` preference and set to false. Provide hover-over help why the preference is not available.

         _Note:_ This step may be difficult to implement.

      1. Left click the tray icon ➔ **Open Zettlr** will show and bring-to-the-front the Zettlr window in the last displayed location in the last displayed size. Linux doesn't support left/right click the tray icon, function is slightly different to Windows 10.

      1. Left click the tray icon ➔ **Quit** will quit Zettlr. Same function as **File** ➔ **Quit** (changes autosaved).

         ![Design Linux Gnome](https://raw.githubusercontent.com/UofA-SPI21-team7/zettlr-assignment/main/images/Zettlr%23175-design-taskbar-with-quit-Fedora-33-Gnome.png)

   1. Linux - KDE desktop:

      1. Left click the tray icon ➔ **Open Zettlr** will show and bring-to-the-front the Zettlr window in the last displayed location in the last displayed size. Linux doesn't support left/right click the tray icon, function is slightly different to Windows 10.

      1. Left click the tray icon ➔ **Quit** will quit Zettlr. Same function as File ➔ Quit (changes autosaved).

         ![Design Linux KDE](https://raw.githubusercontent.com/UofA-SPI21-team7/zettlr-assignment/main/images/Zettlr%23175-design-taskbar-with-quit-Fedora-33-KDE.png)

**Comment by nathanlesage** [comment]
@cskeogh Thank you for the detailed proposal. However, I have a few comments:

0. It is perfectly fine if you just manage to implement this specific amount of features, since this way we will already have a lot of functionality in place that is easy to extend at later points in time.
1. I think it will be more ideal to change "Leave app running in notification area when the window is closed" to "Show in notification area" on macOS. "Leave app running" would sound non-sensical on macOS, since no app is closed by default if all windows have been closed. Furthermore, I don't know if we should word it "when the window is closed" — which window? Any quicklook window? Or the main window? Just keeping it to "Leave the app running in notification area" would make it shorter and imply that, or wouldn't it? I'm not working with Windows on a regular basis, but that would be my first idea.
2. It would be very easy to implement a quick configuration check in `main.ts`, more precisely in the `app.on('window-all-closed')`-event (e.g.: `global.config.get('system.has_tray_icon') === true`): https://github.com/Zettlr/Zettlr/blob/bfb6afb257841d607290226577d38bceab5f7329/source/main.ts#L159-L168 (The reason for this is that, before the main window is being closed, all other windows are closed, so as soon as the main window has been successfully closed, this event will be emitted on every platform)
3. If you were to implement it this way, it seems to me like it would make sense that the default for this option should be "unckeched" on all platforms. It sounds counter-intuitive to me that a writing application would stay open. For messengers such as Slack, it makes sense since there might be other notifications arriving, but any offline app should in my view quit immediately, unless otherwise specified. It could very well be, that users interpret it as being intrusive that the app doesn't quit when the main window is closed.
4. With regard to Linux and the additional libraries:
    1. Would you mind checking whether or not we could add those libraries to some configuration options either for `electron-builder` (which creates the .deb- and .rpm-packages) or `electron-forge` (which packages the app before the installation-packages .deb and .rpm are created) so that these dependencies are shipped with Zettlr or installed alongside?
    2. If that is not the case, it makes sense to implement an additional check during boot ([in this function](https://github.com/Zettlr/Zettlr/blob/develop/source/app/util/environment-check.ts)) that sets an environment variable in the same fashion as `PANDOC_PATH` that indicates whether or not support is given. This variable will then be available also in all BrowserWindow-instances (`process.env.PANDOC_PATH`). Please not that you cannot set environment variables to `undefined` since that would be cast to the string `"undefined"` (I had to learn that lesson the hard way)
    3. Currently, the `Form.vue`-components (located in `common/vue/form/elements`) only have inconsistent support for conditional enabling ([the Button component has](https://github.com/Zettlr/Zettlr/blob/develop/source/common/vue/form/elements/Button.vue)). It would be great to add this support throughout all elements where it makes sense, and enable this in the [Form.vue](https://github.com/Zettlr/Zettlr/blob/develop/source/common/vue/form/Form.vue) component. Then we can define an additional property in the Schemas (e.g. [the advanced one](https://github.com/Zettlr/Zettlr/blob/develop/source/win-preferences/schema/advanced.js)) that disables certain options as necessary.
5. In general, you mention "Changes will be autosaved" — in the current iteration they won't, and I would like to retain the manual saving process. But the window will ask the user anyways before it is being closed.

Wrapping up, the most easy way would just be to implement the following technical changes:

1. Add the mentioned settings option
2. Add an additional check in the `window-all-closed`-event that prevents quitting on non-mac-platforms if the setting is true
3. On click onto the tray icon (or: "Open Zettlr"), please only call the window manager's `showMainWindow`-function. That function will automatically make sure to either show the already existing window, or open a new one, if the main window is in fact closed. https://github.com/Zettlr/Zettlr/blob/bfb6afb257841d607290226577d38bceab5f7329/source/main/modules/window-manager/index.ts#L462-L481

**Comment by cskeogh** [comment]
Hi @nathanlesage thank you for the excellent review and feedback. An updated design is below. Comments welcome.

1. Add `Leave app running in the notification area` (Windows/Linux) and `Show app in the notification area` (MacOS) to **Preferences** ➔ **Advanced**.

   1. Defaults to false (for all operating systems).
   1. Windows and Linux preferences:

      ![Preferences](https://raw.githubusercontent.com/UofA-SPI21-team7/zettlr-assignment/0f63ef3fd7f274f6dd6a6ff5c0fdb80b18c44a97/images/Zettlr%23175-design-preferences-Windows-10-Linux.png)

   1. MacOS preferences:

      ![Preferences](https://raw.githubusercontent.com/UofA-SPI21-team7/zettlr-assignment/0f63ef3fd7f274f6dd6a6ff5c0fdb80b18c44a97/images/Zettlr%23175-design-preferences-MacOS.png)


1. When `Leave app running in the notification area` (Windows/Linux) / `Show app in the notification area` (MacOS) is false, Zettlr design is unchanged.

1. When `Leave app running in the notification area` (Windows/Linux) / `Show app in the notification area` (MacOS) is true:

   1. Zettlr tray icon is visible in notification area when Zettlr is running. Tray icon is visible when Zettlr window is visible too. This is consistent with [Slack app](https://slack.com) and many more apps.

   1. Selecting **File** ➔ **Quit** will quit. This design is unchanged.

   1. Windows 10:

      1. Clicking 🗙 in top-right of Zettlr window title bar will hide Zettlr. Zettlr will not quit.

      1. Left click the tray icon will show and bring-to-the-front the Zettlr window in the last displayed location in the last displayed size.

         ![Design taskbar](https://raw.githubusercontent.com/UofA-SPI21-team7/zettlr-assignment/main/images/Zettlr%23175-design-taskbar.png)

      1. Right click the tray icon ➔ **Quit** will quit Zettlr. Same function as File ➔ Quit. If there are unsaved changes, show and bring-to-the-front the Zettlr window and display the 'There are unsaved changes' modal dialog.

         ![Design Windows 10](https://raw.githubusercontent.com/UofA-SPI21-team7/zettlr-assignment/main/images/Zettlr%23175-design-taskbar-with-quit-Windows-10.png)

   1. MacOS:

      1. Clicking 🗙 in top-right of Zettlr window title bar will quit, Zettlr design is unchanged.

      1. Left click the tray icon ➔ **Open Zettlr** will show and bring-to-the-front the Zettlr window in the last displayed location in the last displayed size. MacOS doesn't support left/right click the tray icon, function is slightly different to Windows 10.

      1. Left click the tray icon ➔ **Quit** will quit Zettlr. Same function as **File** ➔ **Quit**. If there are unsaved changes, show and bring-to-the-front the Zettlr window and display the 'There are unsaved changes' modal dialog.

         ![Design MacOS](https://raw.githubusercontent.com/UofA-SPI21-team7/zettlr-assignment/main/images/Zettlr%23175-design-taskbar-with-quit-MacOS.png)

   1. Linux - Gnome desktop:

      1. Clicking 🗙 in top-right of Zettlr window title bar will hide Zettlr. Zettlr will not quit.

      1. Update `electron-builder` (which creates the .deb- and .rpm-packages) and `electron-forge` (which packages the app before the installation-packages .deb and .rpm are created) so that libappindicator is shipped with Zettlr or installed alongside.

      1. If running Gnome, tray requires gnome-shell extension [AppIndicator Support](https://extensions.gnome.org/extension/615/appindicator-support/) to be installed. It is not appropriate to bundle/auto-install a gnome-shell extension. Instead, detect if [AppIndicator Support](https://extensions.gnome.org/extension/615/appindicator-support/) is installed. Add an additional check during boot [in this function](https://github.com/Zettlr/Zettlr/blob/develop/source/app/util/environment-check.ts) that sets an environment variable that indicates whether or not support is given.

         _Note:_ This step may be difficult to implement.

      1. If [AppIndicator Support](https://extensions.gnome.org/extension/615/appindicator-support/) is not detected, disable (grey-out) `Leave app running in the notification area` preference and set to false. Provide hover-over help why the preference is not available.

      1. Left click the tray icon ➔ **Open Zettlr** will show and bring-to-the-front the Zettlr window in the last displayed location in the last displayed size. Linux doesn't support left/right click the tray icon, function is slightly different to Windows 10.

      1. Left click the tray icon ➔ **Quit** will quit Zettlr. Same function as **File** ➔ **Quit**. If there are unsaved changes, show and bring-to-the-front the Zettlr window and display the 'There are unsaved changes' modal dialog.

         ![Design Linux Gnome](https://raw.githubusercontent.com/UofA-SPI21-team7/zettlr-assignment/main/images/Zettlr%23175-design-taskbar-with-quit-Fedora-33-Gnome.png)

   1. Linux - KDE desktop:

      1. Clicking 🗙 in top-right of Zettlr window title bar will hide Zettlr. Zettlr will not quit.

      1. Left click the tray icon ➔ **Open Zettlr** will show and bring-to-the-front the Zettlr window in the last displayed location in the last displayed size. Linux doesn't support left/right click the tray icon, function is slightly different to Windows 10.

      1. Left click the tray icon ➔ **Quit** will quit Zettlr. Same function as **File** ➔ **Quit**. If there are unsaved changes, show and bring-to-the-front the Zettlr window and display the 'There are unsaved changes' modal dialog.

         ![Design Linux KDE](https://raw.githubusercontent.com/UofA-SPI21-team7/zettlr-assignment/main/images/Zettlr%23175-design-taskbar-with-quit-Fedora-33-KDE.png)

**Comment by nathanlesage** [comment]
>    1. Zettlr tray icon is visible in notification area when Zettlr is running. Tray icon is visible when Zettlr window is visible too. This is consistent with [Slack app](https://slack.com) and many more apps.

This is a little bit weirdly worded, but you basically mean: If Zettlr is running AND the corresponding setting is true, the tray icon will be visible whether or not the main window is also visible, right?
 
>       1. Clicking 🗙 in top-right of Zettlr window title bar will hide Zettlr. Zettlr will not quit.

With "hide Zettlr" you mean (technically) "close the main window, but don't exit the app itself", right?

>       1. Clicking 🗙 in top-right of Zettlr window title bar will quit, Zettlr design is unchanged.

Closing the main window on macOS will _not_ quit the app, but just close the main window.

> [...] MacOS doesn't support left/right click the tray icon, function is slightly different to Windows 10.

Absolutely no problem, I know about the Electron API's limitations :)

> It is not appropriate to bundle/auto-install a gnome-shell extension. Instead, detect if [AppIndicator Support](https://extensions.gnome.org/extension/615/appindicator-support/) is installed. Add an additional check during boot [in this function](https://github.com/Zettlr/Zettlr/blob/develop/source/app/util/environment-check.ts?rgh-link-date=2021-04-08T12%3A42%3A35Z) that sets an environment variable that indicates whether or not support is given.

Sounds reasonable.

> _Note:_ This step may be difficult to implement.

I don't wanna sound like your instructor, but if you manage to pull that off, that'll greatly increase your knowledge and skill in OS-shell programming, so I'd at least do an attempt!

***

That being said: Please excuse the many questions; I've never worked with an actual thought-through design process before implementing something (certainly a limitation of Open Source + Free time + not being a CS graduate).

One last thing that you should know before actually implementing: Zettlr is being translated throughout, that is: There are (almost) no un-translated verbatim English strings in the source code, but everything works via the `trans`-function, and you will need some new translation strings for this. So please observe the following:

1. If you need to show some string to the user, think of an appropriate wording in English (the translations are then being performed by the community), and think of a namespaced identifier. I have not followed a rigid system, unfortunately, but I'm aiming to go for one, so try (but not too hard) to think of something that looks more systematic. Orient yourselves at the already existing trans-calls, i.e. search the codebase for `trans('`, and you should find the strings.
2. If whatever you want to show the user is already translated, and has the same meaning (e.g. an "ok" button doesn't change throughout the app) make sure to look if there is already such a string in the translation database. If so, use that one instead of thinking of a new one.
3. You can find all translation strings on [Zettlr Translate](https://translate.zettlr.com/) (feel free to create an account there to browse the actual contents; you can fully remove the account afterwards. But you can also just look into the language files. However you like). [Here is how it works](https://translate.zettlr.com/getting-started)
4. If you stumble upon strings where I was too lazy to translate them or forgot to do so, please feel free to also change them from the verbatim strings to `trans`-calls. But you obviously don't have to.
5. When you submit your PR, please include a list of translation identifiers --> English translations so that I can add them to Zettlr Translate.

**Comment by cskeogh** [comment]
Hi @nathanlesage, thank you for taking the time to review. Many thanks for your suggestions and code pointers which will invaluable during implementation.

> This is a little bit weirdly worded, but you basically mean: If Zettlr is running AND the corresponding setting is true, the tray icon will be visible whether or not the main window is also visible, right?

Yes. Agree, I did word that weirdly. Corrected.

> With "hide Zettlr" you mean (technically) "close the main window, but don't exit the app itself", right?

Yes. I corrected the wording. No longer use 'hide' because 'hide' isn't clear.

> Closing the main window on macOS will _not_ quit the app, but just close the main window.

Yes. I corrected the design.

----

1. Add `Leave app running in the notification area` (Windows/Linux) and `Show app in the notification area` (MacOS) to **Preferences** ➔ **Advanced**.

   1. Defaults to false (for all operating systems).
   1. Windows and Linux preferences:

      ![Preferences](https://raw.githubusercontent.com/UofA-SPI21-team7/zettlr-assignment/0f63ef3fd7f274f6dd6a6ff5c0fdb80b18c44a97/images/Zettlr%23175-design-preferences-Windows-10-Linux.png)

   1. MacOS preferences:

      ![Preferences](https://raw.githubusercontent.com/UofA-SPI21-team7/zettlr-assignment/0f63ef3fd7f274f6dd6a6ff5c0fdb80b18c44a97/images/Zettlr%23175-design-preferences-MacOS.png)


1. When `Leave app running in the notification area` (Windows/Linux) / `Show app in the notification area` (MacOS) is false, Zettlr design is unchanged.

1. When `Leave app running in the notification area` (Windows/Linux) / `Show app in the notification area` (MacOS) is true:

   1. If Zettlr is running AND the `Leave app running in the notification area` (Windows/Linux) / `Show app in the notification area` (MacOS) is true, the tray icon will be visible (regardless if Zettlr window(s) are visible or not). This is consistent with [Slack app](https://slack.com) and many more apps.

   1. Selecting **File** ➔ **Quit** will quit. This design is unchanged.

   1. Windows 10:

      1. Clicking 🗙 in the window's titlebar will close the window. Zettlr will not quit.

      1. Left click the tray icon will show and bring-to-the-front the Zettlr window in the last displayed location in the last displayed size.

         ![Design taskbar](https://raw.githubusercontent.com/UofA-SPI21-team7/zettlr-assignment/main/images/Zettlr%23175-design-taskbar.png)

      1. Right click the tray icon ➔ **Quit** will quit Zettlr. Same function as File ➔ Quit. If there are unsaved changes, show and bring-to-the-front the Zettlr window and display the 'There are unsaved changes' modal dialog.

         ![Design Windows 10](https://raw.githubusercontent.com/UofA-SPI21-team7/zettlr-assignment/main/images/Zettlr%23175-design-taskbar-with-quit-Windows-10.png)

   1. MacOS:

      1. Clicking 🗙 in the window's titlebar will close the window. Zettlr design is unchanged.

      1. Left click the tray icon ➔ **Open Zettlr** will show and bring-to-the-front the Zettlr window in the last displayed location in the last displayed size. MacOS doesn't support left/right click the tray icon, function is slightly different to Windows 10.

      1. Left click the tray icon ➔ **Quit** will quit Zettlr. Same function as **File** ➔ **Quit**. If there are unsaved changes, show and bring-to-the-front the Zettlr window and display the 'There are unsaved changes' modal dialog.

         ![Design MacOS](https://raw.githubusercontent.com/UofA-SPI21-team7/zettlr-assignment/main/images/Zettlr%23175-design-taskbar-with-quit-MacOS.png)

   1. Linux - Gnome desktop:

      1. Clicking 🗙 in the window's titlebar will close the window. Zettlr will not quit.

      1. Update `electron-builder` (which creates the .deb- and .rpm-packages) and `electron-forge` (which packages the app before the installation-packages .deb and .rpm are created) so that libappindicator is shipped with Zettlr or installed alongside.

      1. If running Gnome, tray requires gnome-shell extension [AppIndicator Support](https://extensions.gnome.org/extension/615/appindicator-support/) to be installed. It is not appropriate to bundle/auto-install a gnome-shell extension. Instead, detect if [AppIndicator Support](https://extensions.gnome.org/extension/615/appindicator-support/) is installed. Add an additional check during boot [in this function](https://github.com/Zettlr/Zettlr/blob/develop/source/app/util/environment-check.ts) that sets an environment variable that indicates whether or not support is given.

         _Note:_ This step may be difficult to implement.

      1. If [AppIndicator Support](https://extensions.gnome.org/extension/615/appindicator-support/) support is not detected, disable (grey-out) `Leave app running in the notification area` preference and set to false. Provide hover-over help why the preference is not available.

      1. Left click the tray icon ➔ **Open Zettlr** will show and bring-to-the-front the Zettlr window in the last displayed location in the last displayed size. Linux doesn't support left/right click the tray icon, function is slightly different to Windows 10.

      1. Left click the tray icon ➔ **Quit** will quit Zettlr. Same function as **File** ➔ **Quit**. If there are unsaved changes, show and bring-to-the-front the Zettlr window and display the 'There are unsaved changes' modal dialog.

         ![Design Linux Gnome](https://raw.githubusercontent.com/UofA-SPI21-team7/zettlr-assignment/main/images/Zettlr%23175-design-taskbar-with-quit-Fedora-33-Gnome.png)

   1. Linux - KDE desktop:

      1. Clicking 🗙 in the window's titlebar will close the window. Zettlr will not quit.

      1. Left click the tray icon ➔ **Open Zettlr** will show and bring-to-the-front the Zettlr window in the last displayed location in the last displayed size. Linux doesn't support left/right click the tray icon, function is slightly different to Windows 10.

      1. Left click the tray icon ➔ **Quit** will quit Zettlr. Same function as **File** ➔ **Quit**. If there are unsaved changes, show and bring-to-the-front the Zettlr window and display the 'There are unsaved changes' modal dialog.

         ![Design Linux KDE](https://raw.githubusercontent.com/UofA-SPI21-team7/zettlr-assignment/main/images/Zettlr%23175-design-taskbar-with-quit-Fedora-33-KDE.png)

**Comment by nathanlesage** [comment]
Looks wonderful!

Again one thing (but that doesn't change your design, imo), would you mind also implementing the "Open Zettlr" menu item on Windows? Even though you can technically just click the tray icon, I'm sure some users would like that (so that the context menu is the same across all platforms -- would also make implementation easier).

Also, would it make sense to word it "Show Zettlr", rather than "Open Zettlr"...? (I'll leave that to you, just a quick thought)

Other than that: Since traybar icons are in general all monochrome, feel free to use a monochrome Icon as well. On macOS a [lowercase zeta-character](https://en.wikipedia.org/wiki/Zeta) would fit best in the overall design, on other platforms it might make sense to just convert the "block" logo to monochrome. But I'll leave that to your taste :)

***

No need to fully paste the full, changed design in here again (saves us some space in the comments)! Thank you again, and sorry for being so nitpicky (it's definitely easy to criticise something you don't implement yourself ...)

**Comment by cskeogh** [comment]
Hi @nathanlesage thank you for the review and wise comments. I've updated the design to "Show Zettlr" (including on Windows). I won't paste the design but you can find the update design [here](https://github.com/UofA-SPI21-team7/zettlr-assignment/wiki/Tray-Design).

On Windows, system tray icons tend to be monochrome, most application tray icons are colour. 
Therefore I propose a colour Zettlr tray icon on Windows, MacOS and Linux. If you are not happy with this design, let me know and we can change the design.

**Comment by nathanlesage** [comment]
@cskeogh Thank you for the update! You are right, application tray icons on Windows are mostly coloured, so that sounds reasonable. However, on macOS it's generally that you are expected to serve a monochrome icon. There are a few apps that don't follow this rule (Nextcloud Clients in their default settings, for instance), but those stick out -- and not for the good. So at least for macOS I'd suggest we use a monochrome icon, a.k.a. the lowercase zeta character. That one should be the best fit for macOS platforms. Is this manageable for you?

**Comment by cskeogh** [comment]
Hi @nathanlesage Thank you for the fast response. I propose MacOS uses a monochrome icon:

![MacOS Tray Icon](https://raw.githubusercontent.com/UofA-SPI21-team7/zettlr-assignment/5bf15e5df73fad2fb88f15af24b80cf92c22036c/images/Zettlr%23175-design-taskbar-with-quit-MacOS.png)

I propose Windows and Linux use the colour Zettlr tray icon. Full design [here](https://github.com/UofA-SPI21-team7/zettlr-assignment/wiki/Tray-Design). Let me know if you would like any other changes to the design.

**Comment by nathanlesage** [comment]
That looks gorgeous! Thank you!

I can't remember exactly, but the zeta on the logo is either using the Lato or Raleway font. So you may want to test it out to keep it "real", but in the end, you have the freedom to choose any font you like, and the icon you have right there is already veeeery good.

So thank you already, I'm actually now really hooked seeing how this will look like in its finished state :)
