### ISSUE TITLE
[ENHANCEMENT/FEATURE] Better Image handling

### ISSUE THREAD

**Issue by nathanlesage** [Zettlr/Zettlr#176]
The app needs better image handling options:

1. Drag and Drop from the Attachments sidebar
2. Always prefer relative links to absolute links
3. Context menu options on images
4. Show the default image save path in the attachments of the parent folder as well for easier navigation

## Roadmap

- [x] Enable dragging and dropping of image file types from the attachment sidebar onto the editor window
- [x] Make sure that relative links are always preferred to absolute links (esp. when they're in a subdirectory of the file's folder)
- [ ] Show the default image path's assets (as set in preferences) in the attachment sidebar as well, even if you are in the parent directory
- [ ] Add a context menu to show the image in its folder
- [ ] Add a context menu to enable basic editing (Resizing and quick cropping; this is a more complex feature that may be branched out to 1.5)

If you have any, please add further ideas here in the comments!

**Comment by davidbosman** [comment]
+1 for the relative links: absolute links make it impossible to add images to a note stored in a synced folder between Mac and Windows: an absiolute link will work on one machine, but not on the other. A relative path should solve that.

Instead of adding basic image editing, wouldn't it be simpler for you to have an 'edit image in...' menu, with the option to define a default image editor? I reckon the majority of users will already own some eidting app, even Preview on Mac or Microsoft Photos on Windows could do those basic manipulations.

**Comment by nathanlesage** [comment]
Concerning the relative links: it's already possible, but currently you have to -- in some circumstances -- shorten the absolute path to a relative one. What I'm proposing is that I program something into the app that automates this job!

Concerning the basic image editing: Yes, I see your point! Would make it easier, definitely.

**Comment by ploum** [comment]
definitely add my voice to the fact that image editing is *not* needed. It will always be less that dedicated editor. Edith with is, imho, the perfect solution.

**Comment by ploum** [comment]
Wondering what you think about : If I drag-n-drop a picture from an external folder, then that picture is copied in the same folder as the note and a relative path is used.

Or is copied into a "picture" subfolder.

Of course, this adds a bit of complexity as moving a note implies moving referenced images (or copying them if they are referenced in multiple notes) but, in a first time, I think that this could possibly be kept for later.
