### ISSUE TITLE
[FEATURE] Add Check/Uncheck Task List Item (Toggle Checkbox) Keyboard Shortcut

### ISSUE THREAD

**Issue by BoltCitizen** [Zettlr/Zettlr#3002]
### Checklist

- [X] Zettlr does not possess this feature (if it does, but the feature doesn't work out for you, propose an enhancement instead.)
- [X] Zettlr's current features cannot be used to approximate this behaviour (otherwise, propose an enhancement instead.)
- [X] I have searched the documentation to make sure I did not overlook it.
- [X] I have searched both open and closed issues to see if someone has already proposed this.

### Feature Proposal

Wanted to express my support for  #1031, which is closed unfortunately.

Comming from OneNote, I miss this feature. In OneNote I could with a shortcut create, check and uncheck a box. Its very handy and saves me from taking my hands off the keyboard. Since I use Zettlr, before OneNote, mainly as a Second Brain, I work with a lot of check boxes.

### Example Workflow

-

### Caveats

-

### Do you wish to attempt implementing this yourself?

No

### Platforms

- [X] Windows
- [X] macOS
- [X] Linux

### Additional Information

-
