### ISSUE TITLE
Drag images in from desktop, option to also move the image to local folder?

### ISSUE THREAD

**Issue by asielen** [Zettlr/Zettlr#335]
When dragging and dropping an image into a note. It would be great to be able to choose if you want to move it into the folder or keep it in place. 

Maybe we could have an option to have the paste image dialog open when dragging and dropping?

**Comment by nathanlesage** [comment]
Sounds reasonable, and I've gotten this request from other sides as well, so yeah, why not!

**Comment by danieltomasz** [comment]
Im for that, but would be better to have possibility of  setting this once in the general option and have 3 options:
*  copy image to predefined folder
*  always ask where to copy
* dont copy

**Comment by asielen** [comment]
Just saw this was marked as stale. Any chance of including this in a future release?

**Comment by nathanlesage** [comment]
Sure! I'm pinning this so that the bot doesn't re-mark this as stale. If someone wants to take up the task of implementing, feel free to propose a PR!

**Comment by zumdar** [comment]
hey I'd also love this! any word about it? sometimes it will ask me if i want to move the image to a local directory, but a lot of times it doesnt :(

**Comment by sds100** [comment]
I'm going to work on this feature. It is something that is stopping me from using Zettlr and I love how Zettlr works with tagging and linking between notes. No other open source note taking app does it this well and simply. I also can't find a decent Android app to work notes made in Zettlr so I might also make an Android app.

The way I'd like it to work is whatever file I am dragging into the editor should be copied to the folder that the note is saved in. I will try to expose settings like @danieltomasz mentioned.

I am going to do it on the master branch because develop is very much a WIP for 2.0. The code to make this work will go [here](https://github.com/Zettlr/Zettlr/blob/master/source/renderer/modules/markdown-editor/hooks/drop-files.js).

I also want this to work when pasting because right now copying a file in the file manager and then pasting just pastes a URI to the file.

Here is my branch https://github.com/sds100/Zettlr/tree/feature/335-copy-file-when-dropping-into-editor

### TODO

**options**
  - [ ] copy to same folder as note
  - [ ] copy image to predefined folder
  - [ ] always ask where to copy
  - [ ] dont copy
- [ ] setting that also does that ^ when pasting.

**Comment by sds100** [comment]
I'm also not sure what the "Default image path" setting does.

**Comment by nathanlesage** [comment]
> I'm going to work on this feature.

Thank you! That sounds great!

> The way I'd like it to work is whatever file I am dragging into the editor should be copied to the folder that the note is saved in. I will try to expose settings like @danieltomasz mentioned.

That should be easy by adding a new setting in the config provider that can have three (or more?) states – I think strings should work just fine; TypeScript can treat them like enums. Then you can access this setting everywhere using `global.config.get`. With regard to adding it to the preferences dialog, it's basically copying and pasting one of the `radio`-types, it should be fairly self-explanatory, and if not, don't hesitate to ask!

> I am going to do it on the master branch because develop is very much a WIP for 2.0.

Please do not implement this on the master branch, since in one or two weeks I will merge the develop into master and begin the beta. You can safely work on develop since at this point there are no major changes being made anymore; anything that's happening now is small fixes here and there, but nothing big.

> The code to make this work will go [here](https://github.com/Zettlr/Zettlr/blob/master/source/renderer/modules/markdown-editor/hooks/drop-files.js?rgh-link-date=2021-07-09T14%3A29%3A49Z).

You're going to need some communication with the main process to make this work, so yes you should check for the config setting in the `drop-files` hook, but in case of a copy-event you should implement a new command (residing in `source/main/commands`) – you can simply copy one of the existing ones for the boilerplate and then implement the functionality. You can then – in this command – return the new file path and handle everything else back in the hook.

> I also want this to work when pasting because right now copying a file in the file manager and then pasting just pastes a URI to the file.

What do you mean by that?

***

Other than that: Again thank you for taking this on; if you have any questions feel free to ask!

**Comment by sds100** [comment]
Quick reply!

Yeah, I'll do it on develop. On Linux the UI is still pretty buggy so I might investigate those issues as well. I really like the old UI much more. 😄

Cool, thanks for the pointers. So does code need to go in `source/main/commands` if it is going to be used in multiple places? Or is it just trying to keep logic out of the hooks? 

I'll explain a bit better 😄 Right now pasting a file that is copied to the clipboard just pastes the uri to the file as text and doesn't link to it. I will try to make it so that it also does the same thing as dragging it into the editor. This probably depends somewhat on the OS that is being used. But if it detects a file uri then it should still be able to copy and create a link to the copied file.

https://user-images.githubusercontent.com/16245954/125097807-66f2b900-e0ce-11eb-8a11-494b589d93fe.mp4

**Comment by sds100** [comment]
Do you manually put the strings in alphabetical order?

**Comment by nathanlesage** [comment]
> On Linux the UI is still pretty buggy so I might investigate those issues as well.

Please do so, since I'm having a hard time making the GUI look better there! Any CSS fixes would be greatly appreciated!

> Or is it just trying to keep logic out of the hooks?

The reason is that the renderer has no access to anything, including the filesystem. So if you want to do anything to the filesystem, you're going to have to do that in main, and writing a new command is the easiest way to accomplish that, since you can then just call `ipcRenderer.invoke('application', { command: 'your-command-name', payload: 'any payload' }).then(returnValue => /* Do something with the returned value from the command */)`

> But if it detects a file uri then it should still be able to copy and create a link to the copied file.

Ah, so you basically wanna generalise that to **any** file? Then we might want to add an additional option differentiating between "Only copy images" or "Copy any file" — or what do you think? (+ the rest?)

> Do you manually put the string resources in alphabetical order?

String resources a.k.a. the possible values for that config option? No, I don't think so, just do what makes sense and is readable!

**Comment by sds100** [comment]
I think for the Linux UI it might be worth using something similar to the old UI because hardcoding your own theme is never going to look native since every Linux user uses a different theme on their system. The old UI looked great I think even though it didn't follow my native theme. If I read correctly, you want to copy the Gnome theme right?

Ah, okay. Yeah that makes sense. This is my first time doing stuff with Electron and Javascript.

Yeah, I would really like to generalise it to all files so that they all show up in the attachments pane but a link is also created to the attachment in the note. I can see why some people would just want images to do that though. Images should still do their special thing which shows a preview than just creating a link.

I couldn't get the strings for the config options to show in the UI. I tried putting them in `static/lang/en-US.json` and the values wouldn't show in the UI. Only the ids for the strings did.

**Comment by nathanlesage** [comment]
> I think for the Linux UI it might be worth using something similar to the old UI because hardcoding your own theme is never going to look native since every Linux user uses a different theme on their system. The old UI looked great I think even though it didn't follow my native theme. If I read correctly, you want to copy the Gnome theme right?

Yeah, that's the problem. I never thought that I could just leave the custom theme … that being said: Feel free to play around until you arrive at something that looks good, then we can still change that later if others complain!

> I couldn't get the strings for the config options to show in the UI. I tried putting them in static/lang/en-US.json and the values wouldn't show in the UI. Only the ids for the strings did.

Oh … :D Alright, here's how you do it:

1. First, declare the option here: https://github.com/Zettlr/Zettlr/blob/develop/source/app/service-providers/types/config-provider.d.ts (Orient yourself at how I did it with the option `autoDarkMode`)
2. Then, put the **default value** (i.e. do not copy around files) in here: https://github.com/Zettlr/Zettlr/blob/develop/source/app/service-providers/assets/get-config-template.ts
3. Then you can retrieve the config value using `global.config.get('identifier')`
4. To allow users editing, add the config value somewhere in the preferences, more exactly here: https://github.com/Zettlr/Zettlr/tree/develop/source/win-preferences/schema (Each file is one of the tabs, I'd argue it makes most sense to put your option either in "Editor" or in "General"). Copy over one of the existing radios and adapt to the new config option

Then, the rest is coding the feature as I indicated!

**Comment by sds100** [comment]
Thanks! I'll play around with the theming after this 😄. I will need to if I want to use this feature day to day,

**Comment by sds100** [comment]
I am guessing the FSAL should be used to copy the file to Zettlr? FSAL.findFile() currently returns null when I give it the path to the file being dragged. Is that because the FSAL only for the workspace files?

**Comment by nathanlesage** [comment]
> I am guessing the FSAL should be used to copy the file to Zettlr?

No, the FSAL is simply for rendering the file tree itself. That's an option where you should simply use the copyFile prop (attention: use the promises API). Like so:

```javascript
import { promises as fs } from 'fs'

// ... snip ...

await fs.copyFile(source, target)

// Later, return the path of the destination for the file, i.e.:
return target
```

Info: https://nodejs.org/api/fs.html#fs_fspromises_copyfile_src_dest_mode

**Comment by sds100** [comment]
Ohh, okay. I thought it was an abstraction layer for the _whole_ file system. Yeah, I used that API when I was playing around with the master branch. Thanks again

**Comment by sds100** [comment]
I got the first option to work but how do I make it not show the id of the string resource? (bottom right)

![Screenshot_20210710_124923](https://user-images.githubusercontent.com/16245954/125161971-5c432d00-e17d-11eb-948d-52027001cd42.png)

**Comment by sds100** [comment]
@danieltomasz how would you expect the "always ask where to copy" option to work? Which folders should it allow you to choose from?

**Comment by sds100** [comment]
@nathanlesage dragging files in from the attachments pane creates an absolute path rather than a relative path (i'd prefer this). should i create a separate issue for this? I'm not sure if it is a bug or a feature from looking at the code.

**Comment by tifish** [comment]
Local image support is important. Typora makes me feel like in Microsoft Word when pasting images. Will Zettlr implements variables like ${filename} to customize the local image path?

Image options in Typora:

![image](https://user-images.githubusercontent.com/16101136/142795498-8bf85340-c9ed-43ca-a2b4-efb40284a11d.png)

**Comment by nathanlesage** [comment]
> if the folder to place the image could be set to assets/, that would also make it cross compatible with the Textbundle format.

That is already happening when you copy and paste images. Plus, Zettlr does export and import Textbundles. Support has been added years ago!

**Comment by leowill01** [comment]
> > if the folder to place the image could be set to assets/, that would also make it cross compatible with the Textbundle format.
> 
> That is already happening when you copy and paste images. Plus, Zettlr does export and import Textbundles. Support has been added years ago!

Ah, I did not know there was a separate functionality when you copy/paste an image into the doc versus drag & drop. This seems to be an adequate workaround for now! But extending this to drag/drop would be a happy QOL improvement.
