### ISSUE TITLE
[ENHANCEMENT] New Shortcuts Mega-Thread

### ISSUE THREAD

**Issue by nathanlesage** [Zettlr/Zettlr#783]
Alright, I'm annoyed by all these small issues with only one new shortcut, so let's keep the discussion central.

What you can comment on in this thread: Propose new shortcuts for already existing functionality.

## Preconditions

1. The shortcut is free according to [this chart (more experienced users, please double check on all platforms)](https://www.zettlr.com/shortcuts)
2. The function already exists and henceforth only needs to be additionally triggered by the shortcut.
3. There's a reasonable shortcut for all three platforms (i.e. NOT Ctrl+Shift+E to focus the editor on Windows and then Cmd+Alt+? for macOS as this would be counter intuitive)

Feel free to drop them in, then we can add them in 1.7, but no guarantee if I encounter problems while implementing!

## Already on the list

- [x] [`Ctrl/Cmd+Shift+L`](https://github.com/Zettlr/Zettlr/issues/421) to copy the ID of the current note (as opposed to paste a new one)
- [x] [`F2`](https://github.com/Zettlr/Zettlr/issues/372) for Windows and Linux to trigger a rename
- [x] [`Ctrl+Mousewheel`](https://github.com/Zettlr/Zettlr/issues/571) for zooming on Windows/Linux, `pinch`ing for macOS (EDIT: Pinching is not detectable, it counts as scrolling … this is just broken. So no luck for pinching, but I'll enable Cmd+mousewheel … oh boy …)
- [X] `Cmd/Ctrl+[0-9]` select tab 1-10 or the recent documents 1-10. Defaults to recent documents.
- [X] `Ctrl+Tab` select next tab
- [X] `Ctrl+Shift+Tab` select previous tab
- [X] `Cmd/Ctrl+W` Closes the active tab. If no tabs are opened, revert to current behaviour and close window. (Implemented. To close the window immediately, use `Cmd/Ctrl+Shift+W`)

**Comment by kyaso** [comment]
Although `Ctrl/Cmd+F` already exists, would be nice to have the following extensions:
1. `Ctrl/Cmd+F` while some text is highlighted: Automatically search for the highlighted text in the currently open file
2. `Ctrl/Cmd+Shift+F` while some text is highlighted: Automatically perform a global search (i.e., search bar) for the highlighted text

**Comment by enricllagostera** [comment]
With the new tab functionality, it would be interesting to have shortcuts for tab navigation / manipulation (drawing from browsers):

1. `Ctrl/Cmd+[0-1]` - Go to tab in given order (left to right). I know this one overlaps with the recent documents shortcut, but it looks to me like a much more useful functionality (as the order of documents being called is constantly visible instead of memorized). It also would need to be coupled with the possibility of dragging tabs to re-order them, probably;
2. `Ctrl/Cmd+Tab` and `Ctrl/Cmd+Shift+Tab` for cycling active tabs;
3. `Ctrl/Cmd+W` to close current tab;

**Comment by nathanlesage** [comment]
> I know this one overlaps with the recent documents shortcut, but it looks to me like a much more useful functionality (as the order of documents being called is constantly visible instead of memorized).

I'll do a poll on Twitter, and here: **Poll: React to this comment with a rocket 🚀 if you want the tabs to be addressed by the shortcuts (instead of the recent docs). React with party 🎉 if you want to retain the current functionality.**

> Ctrl/Cmd+W to close current tab;

Except there's none open, then close window, as already!

**Comment by KarlClinckspoor** [comment]
I tested the new shortcuts for the tabs, and it got me very confused. If I press `CTRL+2` several times, it keeps switching between the most recently opened tab and some other, `CTRL+3` switches between the most recently opened tab and two others, and so on. Is this the expected behavior? I find it confusing.

On the other hand, I thought of these shortcuts:

1. `Ctrl/Cmd + G` will add two backticks, to add code, like `Ctrl+B` adds bold. 
2. `Ctrl/Cmd + Shift + G` will add two sets of triple backticks in a new line, with the cursor in the middle.
3. `Ctrl/Cmd + /` will search for the ID of the current file, to check backreferences easily, although this can be achieved with the new shortcut to copy the current ID, then the shortcut to search, then paste it, but that seems somewhat cumbersome.

**Comment by nathanlesage** [comment]
> I tested the new shortcuts for the tabs, and it got me very confused

The tabs don't have shortcuts at the moment.

**Comment by nathanlesage** [comment]
Quick update concerning the shortcuts: While here on the issue the results are quite clear, over on Twitter (just as I suspected) there are folks relying on the `Cmd/Ctrl+[0-9]`-shortcuts to react to recent documents, so at least for the time being, I'd suggest implementing a setting that defaults to recent documents, but can be toggled to make the shortcuts react to the tabs instead (at least the first ten; funfact just tested it out on Chrome and this douche was skipping a tab 😠)

**Comment by IpeTek** [comment]
I wish there was a shortcut for collapsing/expanding all the headers at once? Would make Zettlr more useful in outlining. 

I checked and found no reason not to use `Ctlr/Cmd + O` for this.

**Comment by locness3** [comment]
You should make the list on the first comment a markdown check list (`- [ ] something`)

**Comment by nathanlesage** [comment]
Rejoice! I added all shortcuts that were safe to add and agreed upon. But I decided to completely ditch selection reccent files using shortcuts, first because it's really not often used and two because a lot of you rightfully stated that it's somewhat counterintuitive.

**Comment by GregSchofield-Perth-Aus** [comment]
> I wish there was a shortcut for collapsing/expanding all the headers at once? Would make Zettlr more useful in outlining.
> 
> I checked and found no reason not to use `Ctlr/Cmd + O` for this.

Would very mush support this shortcut, very useful for long structured documents.

**Comment by pjembley** [comment]
Heya! I've just moved to Zettlr as a note-taking app, and I'm struggling to find some features present in other text-editors.
I have a habit of taking fast notes, then formatting them later. As such, I need a button or key shortcut to quickly turn some lines into a bulleted list, as you can do in this very comment box :) I've hunted and hunted, but can't find one. I'm not completely sure my Pandoc is working, so maybe it's that... Can you enlighten me? If it's not a thing, I'd love to see this feature.
